
AddHelpInfo("Bloodthirsty Hunter","Somebody spotted them near local sea region at (410, 1532)")
AddHelpInfo("White Finned Shark","Somebody spotted them near local sea region at (3238, 3344)")
AddHelpInfo("Ruby Dolphin","Somebody spotted them near local sea region at (1020,3240)")
AddHelpInfo("Tempest Sea Jelly","Somebody spotted them near local sea region at (1797, 200)")
AddHelpInfo("Berserk Boxeroo","Somebody spotted them near local sea region at (1071, 2600)")
AddHelpInfo("Chameleon Squid","Somebody spotted them near local sea region at (41,600)")
AddHelpInfo("Undead Warrior","Somebody spotted them near local sea region at (493, 1640)")
AddHelpInfo("Whacky Lamb","Somebody spotted them near local sea region at (1952, 2657)")
AddHelpInfo("Meadow Deer","Somebody spotted them near local sea region at (1440, 2640)")
AddHelpInfo("Grass Tortoise","Somebody spotted them near local sea region at (1900, 2427)")
AddHelpInfo("Grassland Wolf","Somebody spotted them near local sea region at (1034, 2680)")
AddHelpInfo("Grassland Elk","Somebody spotted them near local sea region at (1320,2640)")
AddHelpInfo("Mature Grass Tortoise","Somebody spotted them near local sea region at (1150,3072)")
AddHelpInfo("Slowpoke Snail","Somebody spotted them near local sea region at (1200,2680)")
AddHelpInfo("Spearhead Shark","Somebody spotted them near local sea region at (3238, 3344)")
AddHelpInfo("Stinging Beak","Somebody spotted them near local sea region at (835,2540)")
AddHelpInfo("Greedy Shroom","Somebody spotted them near local sea region at (1497,2788)")
AddHelpInfo("Terra Soldier Leader","Somebody spotted them near local sea region at (461, 2670)")
AddHelpInfo("Terra Captain","Somebody spotted them near local sea region at (296, 2530)")
AddHelpInfo("Terra Warrior Leader","Somebody spotted them near local sea region at (293, 2235)")
AddHelpInfo("Shocking Sea Jelly","Somebody spotted them near local sea region at (2300, 202)")
AddHelpInfo("Chimera","Somebody spotted them near local sea region at (600, 2385)")
AddHelpInfo("Vicious Undead Warrior","Somebody spotted them near local sea region at (782, 1051)")
AddHelpInfo("Vicious Pumpkin Knight","Somebody spotted them near local sea region at (564, 3948)")
AddHelpInfo("Corrupted Guardian Angel","Somebody spotted them near local sea region at (285, 2053)")
AddHelpInfo("Vicious Baby Squid","Somebody spotted them near local sea region at (1300, 350)")
AddHelpInfo("Angelic Panda","Somebody spotted them near local sea region at (1555, 2516)")
AddHelpInfo("Mad Tribal Villager","Somebody spotted them near local sea region at (531,2235)")
AddHelpInfo("Icky Seaweed","Somebody spotted them near local sea region at (3800,3000)")
AddHelpInfo("Steel Mummy","Somebody spotted them near local sea region at (400, 1380)")
AddHelpInfo("Fish Bone","Somebody spotted them near local sea region at (41, 240)")
AddHelpInfo("Seaweed","Somebody spotted them near local sea region at (41, 200)")
AddHelpInfo("Black Finned Shark","Somebody spotted them near local sea region at (2438,3344)")
AddHelpInfo("Dark Mud Monster","Somebody spotted them near local sea region at (540, 1831)")
AddHelpInfo("Thickskin Lizard","Somebody spotted them near local sea region at (682, 2633)")
AddHelpInfo("Cuddly Lamb","Somebody spotted them near local sea region at (2027, 2600)")
AddHelpInfo("Azure Siren","Somebody spotted them near local sea region at (2800, 200)")
AddHelpInfo("Sturdy Rock Golem","Somebody spotted them near local sea region at (580, 1660)")
AddHelpInfo("Tusk Battle Boar","Somebody spotted them near local sea region at (1251, 2962)")
AddHelpInfo("Mystic Shrub","Somebody spotted them near local sea region at (2150, 2528)")
AddHelpInfo("Mystic Flower","Somebody spotted them near local sea region at (1545, 3080)")
AddHelpInfo("Elite Werewolf Archer","Somebody spotted them near local sea region at (353, 2435)")
AddHelpInfo("Elite Werewolf Warrior","Somebody spotted them near local sea region at (499, 1398)")
AddHelpInfo("Elite Tribal Warrior","Somebody spotted them near local sea region at (591, 2235)")
AddHelpInfo("Great Polliwog","Somebody spotted them near local sea region at (41,600)")
AddHelpInfo("Wolf","Somebody spotted them near local sea region at (700, 2795)")
AddHelpInfo("Giant Lizard","Somebody spotted them near local sea region at (650, 2053)")
AddHelpInfo("Lumbering Treant","Somebody spotted them near local sea region at (400, 2053)")
AddHelpInfo("Huge Spiky Stramonium","Somebody spotted them near local sea region at (400, 1260)")
AddHelpInfo("Poisonous Sea Jelly","Somebody spotted them near local sea region at (1300, 350)")
AddHelpInfo("Treant Terror","Somebody spotted them near local sea region at (600, 2385)")
AddHelpInfo("Horrific Cursed Corpse","Somebody spotted them near local sea region at (320, 1300)")
AddHelpInfo("Fearsome Tortoise","Somebody spotted them near local sea region at (905, 2540)")
AddHelpInfo("Treant","Somebody spotted them near local sea region at (591, 2235)")
AddHelpInfo("Deadly Skeletal Archer","Somebody spotted them near local sea region at (670, 1061)")
AddHelpInfo("Skeletal Warrior Leader","Somebody spotted them near local sea region at (320, 1380)")
AddHelpInfo("Berserk Sea Jelly","Somebody spotted them near local sea region at (1020,3240)")
AddHelpInfo("Tempest Sea Jelly","Somebody spotted them near local sea region at (2538, 3700)")
AddHelpInfo("Werewolf Warrior","Somebody spotted them near local sea region at (700, 2795)")
AddHelpInfo("Werewolf Warrior Leader","Somebody spotted them near local sea region at (353, 2435)")
AddHelpInfo("Old Sawtooth Shark","Somebody spotted them near local sea region at (2438,3344)")
AddHelpInfo("Crimson Siren","Somebody spotted them near local sea region at (1800, 200)")
AddHelpInfo("Killer Shroom","Somebody spotted them near local sea region at (1564, 2626)")
AddHelpInfo("Agile Tribal Villager","Somebody spotted them near local sea region at (690, 1200)")
AddHelpInfo("Stramonium","Somebody spotted them near local sea region at (1297, 2846)")
AddHelpInfo("Owlie","Somebody spotted them near local sea region at (1410, 2600)")
AddHelpInfo("Mermaid","Somebody spotted them near local sea region at (1050, 2100)")
AddHelpInfo("Mini Bee","Somebody spotted them near local sea region at (2019,2720)")
AddHelpInfo("Piglet","Somebody spotted them near local sea region at (1575,2516)")
AddHelpInfo("Pumpkin Knight","Somebody spotted them near local sea region at (564, 2800)")
AddHelpInfo("Mud Monster","Somebody spotted them near local sea region at (875, 2660)")
AddHelpInfo("Blackout Squid","Somebody spotted them near local sea region at (1050, 1880)")
AddHelpInfo("Floating Seaweed","Somebody spotted them near local sea region at (1391, 1000)")
AddHelpInfo("Prowling Blood Polliwog","Somebody spotted them near local sea region at (2300, 201)")
AddHelpInfo("Rookie Boxeroo","Somebody spotted them near local sea region at (1410, 2600)")
AddHelpInfo("Forest Spirit","Somebody spotted them near local sea region at (2150, 2600)")
AddHelpInfo("Bandit","Somebody spotted them near local sea region at (986, 3012)")
AddHelpInfo("Bandit Leader - Adder","Somebody spotted them near local sea region at (1038, 3039)")
AddHelpInfo("Electric Sea Jelly","Somebody spotted them near local sea region at (1700, 1900)")
AddHelpInfo("Ocean Water Dancer","Somebody spotted them near local sea region at (1610, 3240)")
AddHelpInfo("Forest Hunter","Somebody spotted them near local sea region at (881, 1484)")
AddHelpInfo("Stone Golem","Somebody spotted them near local sea region at (461, 2530)")
AddHelpInfo("Guardian Angel","Somebody spotted them near local sea region at (822, 1210)")
AddHelpInfo("Sea Jelly","Somebody spotted them near local sea region at (41, 200)")
AddHelpInfo("Sleepy Snail","Somebody spotted them near local sea region at (2150, 2528)")
AddHelpInfo("Silk Shark","Somebody spotted them near local sea region at (2538, 3700)")
AddHelpInfo("Armored Crab","Somebody spotted them near local sea region at (1707, 2477)")
AddHelpInfo("Armored King Crab","Somebody spotted them near local sea region at (1767, 2497)")
AddHelpInfo("Iron Mummy","Somebody spotted them near local sea region at (499, 1490)")
AddHelpInfo("Iron Golem","Somebody spotted them near local sea region at (461, 2530)")
AddHelpInfo("Tribal Shaman","Somebody spotted them near local sea region at (580, 1200)")
AddHelpInfo("Tribal Villager","Somebody spotted them near local sea region at (489, 1388)")
AddHelpInfo("Elite Tribal Warrior","Somebody spotted them near local sea region at (798, 2076)")
AddHelpInfo("Palace Guard","Somebody spotted them near local sea region at (410,1620)")
AddHelpInfo("Sentry Crab","Somebody spotted them near local sea region at (1767, 2497)")
AddHelpInfo("Skeleton Fish","Somebody spotted them near local sea region at (3800,3000)")
AddHelpInfo("Lizard Warrior","Somebody spotted them near local sea region at (305, 2670)")
AddHelpInfo("Lizard Warrior Leader","Somebody spotted them near local sea region at (293, 2235)")
AddHelpInfo("Air Porky","Somebody spotted them near local sea region at (1297, 2846)")
AddHelpInfo("Small Treant","Somebody spotted them near local sea region at (650, 2053)")
AddHelpInfo("Evil Undead Warrior","Somebody spotted them near local sea region at (530, 2053)")
AddHelpInfo("Evil Pumpkin Knight","Somebody spotted them near local sea region at (300, 1562)")
AddHelpInfo("Evil Water Dancer","Somebody spotted them near local sea region at (1700, 1900)")
AddHelpInfo("Evil Skeleton Fish","Somebody spotted them near local sea region at (2800, 200)")
AddHelpInfo("Evil Blood Polliwog","Somebody spotted them near local sea region at (1800, 200)")
AddHelpInfo("Feral Blood Polliwog","Somebody spotted them near local sea region at (2300, 200)")
AddHelpInfo("Bear Cub","Somebody spotted them near local sea region at (1850, 2804)")
AddHelpInfo("White Owlie","Somebody spotted them near local sea region at (1320,2640)")
AddHelpInfo("Rock Golem","Somebody spotted them near local sea region at (632, 2533)")
AddHelpInfo("Barbaric Bee","Somebody spotted them near local sea region at (1247,2776)")
AddHelpInfo("Wild Seaweed","Somebody spotted them near local sea region at (2384, 2866)")
AddHelpInfo("Mad Boar","Somebody spotted them near local sea region at (865, 2915)")
AddHelpInfo("Sakura 13 Warship","Somebody spotted them near local sea region at (1800, 1100)")
AddHelpInfo("Sakura 13 Support Ship","Somebody spotted them near local sea region at (1800, 1100)")
AddHelpInfo("Sakura 13 Pirate Command Ship","Somebody spotted them near local sea region at (1800, 1100)")
AddHelpInfo("Wandering Mermaid","Somebody spotted them near local sea region at (3384, 150)")
AddHelpInfo("Octopus","Somebody spotted them near local sea region at (3460, 1960)")
AddHelpInfo("Marsh Spirit","Somebody spotted them near local sea region at (1932, 2617)")
AddHelpInfo("Needle of Stramonium","Somebody spotted them near local sea region at (785, 2374)")
AddHelpInfo("Oyster","Somebody spotted them near local sea region at (1787, 2467)")
AddHelpInfo("Smuggler","Somebody spotted them near local sea region at (1570, 2984)")
AddHelpInfo("Cursed Corpse","Somebody spotted them near local sea region at (320, 1380)")


--魔女之海
AddHelpInfo("Shadow Siren","Somebody spotted them near Magical Ocean region at (2852, 1048)")
AddHelpInfo("Tempest Sea Jelly","Somebody spotted them near Magical Ocean region at (41,1052)")
AddHelpInfo("Feral Wolf","Somebody spotted them near Magical Ocean region at (1420,3251)")
AddHelpInfo("Cursed Seaweed","Somebody spotted them near Magical Ocean region at (1600, 2852)")
AddHelpInfo("Cursed Mermaid","Somebody spotted them near Magical Ocean region at (3500, 1100)")
AddHelpInfo("Humpy Camel","Somebody spotted them near Magical Ocean region at (825, 3323)")
AddHelpInfo("Sluggish Squid","Somebody spotted them near Magical Ocean region at (1248, 2300)")
AddHelpInfo("Gigantic Melon","Somebody spotted them near Magical Ocean region at (591,3013)")
AddHelpInfo("Big Scorpion","Somebody spotted them near Magical Ocean region at (1130, 3505)")
AddHelpInfo("Big Eyed Polliwog","Somebody spotted them near Magical Ocean region at (3596, 2856)")
AddHelpInfo("Terra Elder","Somebody spotted them near Magical Ocean region at (1298, 3056)")
AddHelpInfo("Terra Artificer","Somebody spotted them near Magical Ocean region at (1298, 3056)")
AddHelpInfo("Terra Captain","Somebody spotted them near Magical Ocean region at (1298, 3056)")
AddHelpInfo("Terra Warrior Leader","Somebody spotted them near Magical Ocean region at (1298, 3056)")
AddHelpInfo("Sand Crab","Somebody spotted them near Magical Ocean region at (1298, 3056)")
AddHelpInfo("Cavalier","Somebody spotted them near Magical Ocean region at (1200, 2930)")
AddHelpInfo("Starving Wolf","Somebody spotted them near Magical Ocean region at (549,2901)")
AddHelpInfo("Captain Fickle","Somebody spotted them near Magical Ocean region at (1496, 3426)")
AddHelpInfo("Berserk Siren Guard","Somebody spotted them near Magical Ocean region at (1000,1052)")
AddHelpInfo("Berserk Mermaid Protector","Somebody spotted them near Magical Ocean region at (1000,1052)")
AddHelpInfo("Fish Bone","Somebody spotted them near Magical Ocean region at (41,1052)")
AddHelpInfo("Phantom Tree","Somebody spotted them near Magical Ocean region at (845, 2987)")
AddHelpInfo("Lizard King","Somebody spotted them near Magical Ocean region at ( 1495, 2879)")
AddHelpInfo("Seaweed","Somebody spotted them near Magical Ocean region at (760, 3750)")
AddHelpInfo("Siren Queen","Somebody spotted them near Magical Ocean region at (1752, 1048)")
AddHelpInfo("Tanned Skeleton Fish","Somebody spotted them near Magical Ocean region at (1248, 2300)")
AddHelpInfo("Tanned Siren Guard","Somebody spotted them near Magical Ocean region at (1752, 1048)")
AddHelpInfo("Tanned Mermaid Protector","Somebody spotted them near Magical Ocean region at (2252, 1648)")
AddHelpInfo("Dry Mystic Shrub","Somebody spotted them near Magical Ocean region at (953, 3476)")
AddHelpInfo("Azure Siren","Somebody spotted them near Magical Ocean region at (1252,1048)")
AddHelpInfo("Jack the Pirate's Warship","Somebody spotted them near Magical Ocean region at (1848, 2300)")
AddHelpInfo("Jack the Pirate's Sailor","Somebody spotted them near Magical Ocean region at (1496, 3426)")
AddHelpInfo("Jack the Pirate's Support Ship","Somebody spotted them near Magical Ocean region at (1848, 2300)")
AddHelpInfo("Jack the Pirate's Command Ship","Somebody spotted them near Magical Ocean region at (1848, 2300)")
AddHelpInfo("Horrific Siren Guard","Somebody spotted them near Magical Ocean region at (1752, 1048)")
AddHelpInfo("Horrific Mermaid Protector","Somebody spotted them near Magical Ocean region at (2252, 1648)")
AddHelpInfo("Raging Electric Sea Jelly","Somebody spotted them near Magical Ocean region at (3500, 2300)")
AddHelpInfo("Old Ruby Dolphin","Somebody spotted them near Magical Ocean region at (3500, 2300)")
AddHelpInfo("Old Ruby Dolphin","Somebody spotted them near Magical Ocean region at (3500,1900)")
AddHelpInfo("Crimson Siren","Somebody spotted them near Magical Ocean region at (1252,1048)")
AddHelpInfo("Mermaid Queen","Somebody spotted them near Magical Ocean region at (2252, 1648)")
AddHelpInfo("Swift Skeleton Fish","Somebody spotted them near Magical Ocean region at (2330,3430)")
AddHelpInfo("Bewitching Siren","Somebody spotted them near Magical Ocean region at (800, 2400)")
AddHelpInfo("Blackarrow Squid","Somebody spotted them near Magical Ocean region at (2330,2852)")
AddHelpInfo("Mudman","Somebody spotted them near Magical Ocean region at (1400, 3390)")
AddHelpInfo("Stealth Great Polliwog","Somebody spotted them near Magical Ocean region at (800, 1052)")
AddHelpInfo("Killer Cactus","Somebody spotted them near Magical Ocean region at (1400, 3231)")
AddHelpInfo("Sandy Shroom","Somebody spotted them near Magical Ocean region at (1288, 3410)")
AddHelpInfo("Sandy Tortoise","Somebody spotted them near Magical Ocean region at (1130, 3235)")
AddHelpInfo("Sand Brigand","Somebody spotted them near Magical Ocean region at (632, 3240)")
AddHelpInfo("Sand Bandit","Somebody spotted them near Magical Ocean region at (1288, 3251)")
AddHelpInfo("Sand Bandit Leader - Garet","Somebody spotted them near Magical Ocean region at (1153,3007)")
AddHelpInfo("Sand Raider","Somebody spotted them near Magical Ocean region at (984, 2962)")
AddHelpInfo("Electric Sea Jelly","Somebody spotted them near Magical Ocean region at (2588, 544)")
AddHelpInfo("Ancient Siren Archer","Somebody spotted them near Magical Ocean region at (2852, 1048)")
AddHelpInfo("Ancient Siren Guard","Somebody spotted them near Magical Ocean region at (800, 1600)")
AddHelpInfo("Ancient Siren","Somebody spotted them near Magical Ocean region at (3500, 1500)")
AddHelpInfo("Ancient Bewitching Siren","Somebody spotted them near Magical Ocean region at (800, 1600)")
AddHelpInfo("Ancient Mermaid Protector","Somebody spotted them near Magical Ocean region at (800, 1600)")
AddHelpInfo("Scavenger Fish Bone","Somebody spotted them near Magical Ocean region at (3596, 2856)")
AddHelpInfo("Man-Eating Spider","Somebody spotted them near Magical Ocean region at (1048, 2921)")
AddHelpInfo("Sea Jelly","Somebody spotted them near Magical Ocean region at (41, 550)")
AddHelpInfo("Hopping Lizard","Somebody spotted them near Magical Ocean region at (815, 2967)")
AddHelpInfo("Water Dancer","Somebody spotted them near Magical Ocean region at (2330,2852)")
AddHelpInfo("Skeleton Fish","Somebody spotted them near Magical Ocean region at (41,1052)")
AddHelpInfo("Melon","Somebody spotted them near Magical Ocean region at (1120, 3455)")
AddHelpInfo("Cactus","Somebody spotted them near Magical Ocean region at (993,3506)")
AddHelpInfo("Wolf Cub","Somebody spotted them near Magical Ocean region at (591,3013)")
AddHelpInfo("Baby Squid","Somebody spotted them near Magical Ocean region at (760, 3750)")
AddHelpInfo("Baby Scorpion","Somebody spotted them near Magical Ocean region at (1130, 3505)")
AddHelpInfo("Feral Siren","Somebody spotted them near Magical Ocean region at (1252, 1648)")
AddHelpInfo("Evil Great Polliwog","Somebody spotted them near Magical Ocean region at (3596, 3456)")
AddHelpInfo("Feral Ruby Dolphin","Somebody spotted them near Magical Ocean region at (800, 1600)")
AddHelpInfo("Feral Fish Bone","Somebody spotted them near Magical Ocean region at (800, 1052)")
AddHelpInfo("Great Feral Polliwog","Somebody spotted them near Magical Ocean region at (3596, 3456)")
AddHelpInfo("Swift Cyclonic Sea Jelly","Somebody spotted them near Magical Ocean region at (3500, 1100)")
AddHelpInfo("Amethyst Dolphin","Somebody spotted them near Magical Ocean region at (800, 1600)")

--深蓝群岛
AddHelpInfo("Shadow Mermaid","Somebody spotted them near Deep Blue sea region at (2932, 2030)")
AddHelpInfo("Little White Deer","Somebody spotted them near Deep Blue sea region at (1250,288)")
AddHelpInfo("Ruby Dolphin","Somebody spotted them near Deep Blue sea region at (1250, 860)")
AddHelpInfo("Frenzied Siren","Somebody spotted them near Deep Blue sea region at (2688, 3508)")
AddHelpInfo("Frenzied Wolf","Somebody spotted them near Magical Ocean region at (2322, 2965)")
AddHelpInfo("Northern Snail","Somebody spotted them near Deep Blue sea region at (792, 718)")
AddHelpInfo("Chameleon Squid","Somebody spotted them near Deep Blue sea region at (1250, 860)")
AddHelpInfo("Infant Icy Dragon","Somebody spotted them near Deep Blue sea region at (2800, 621)")
AddHelpInfo("Snowy Piglet","Somebody spotted them near Magical Ocean region at (775, 288)")
AddHelpInfo("Undead Archer","Somebody spotted them near Deep Blue sea region at (2692,401)")
AddHelpInfo("Atrocious Yeti King","Somebody spotted them near Magical Ocean region at (880, 894)")
AddHelpInfo("Long Hair Crab","Somebody spotted them near Deep Blue sea region at (3657,2695)")
AddHelpInfo("Mature Ruby Dolphin","Somebody spotted them near Deep Blue sea region at (141, 2707)")
AddHelpInfo("Cumbersome Snowman","Somebody spotted them near Deep Blue sea region at (2436, 445)")
AddHelpInfo("Cumbersome Yeti","Somebody spotted them near Deep Blue sea region at (2742, 510)")
AddHelpInfo("Spearhead Shark","Somebody spotted them near Deep Blue sea region at (141, 2707)")
AddHelpInfo("White Cap Sea Jelly","Somebody spotted them near Deep Blue sea region at (141, 672)")
AddHelpInfo("Naive Snow Doll","Somebody spotted them near Deep Blue sea region at (1010, 708)")
AddHelpInfo("Great Polar Bear","Somebody spotted them near Deep Blue sea region at (3057, 647)")
AddHelpInfo("Playful Snow Doll","Somebody spotted them near Deep Blue sea region at (1548, 532)")
AddHelpInfo("Vicious Mermaid","Somebody spotted them near Deep Blue sea region at (3442, 858)")
AddHelpInfo("Frantic Lizardman","Somebody spotted them near Deep Blue sea region at (2665, 3103)")
AddHelpInfo("Crazy Sheep","Somebody spotted them near Deep Blue sea region at (2204, 540)")
AddHelpInfo("Steel-shell Snail","Somebody spotted them near Deep Blue sea region at (2683, 621)")
AddHelpInfo("Fish Bone","Somebody spotted them near Deep Blue sea region at (3268, 150)")
AddHelpInfo("Little Deer","Somebody spotted them near Magical Ocean region at (1098, 288)")
AddHelpInfo("Seaweed","Somebody spotted them near Deep Blue sea region at (41, 592)")
AddHelpInfo("Sailor Squirt","Somebody spotted them near Magical Ocean region at (703, 427)")
AddHelpInfo("Sailor Squidy","Somebody spotted them near Deep Blue sea region at (1606, 520)")
AddHelpInfo("Siren Archer","Somebody spotted them near Deep Blue sea region at (3358, 3644)")
AddHelpInfo("Black Finned Shark","Somebody spotted them near Deep Blue sea region at (965, 3384)")
AddHelpInfo("Beardy Pirate Warship","Somebody spotted them near Deep Blue sea region at (710, 1492)")
AddHelpInfo("Beardy Pirate Support Ship","Somebody spotted them near Deep Blue sea region at (710, 1492)")
AddHelpInfo("Beardy Pirate Command Ship","Somebody spotted them near Deep Blue sea region at (710, 1492)")
AddHelpInfo("Topaz Dolphin","Somebody spotted them near Deep Blue sea region at (2376,1787)")
AddHelpInfo("Hungry Fish Bone","Somebody spotted them near Deep Blue sea region at (141, 2707)")
AddHelpInfo("Polar Bear","Somebody spotted them near Magical Ocean region at (1886, 520)")
AddHelpInfo("Elite Lizardman Warrior","Somebody spotted them near Deep Blue sea region at (2665, 3103)")
AddHelpInfo("Elite Skeletal Archer","Somebody spotted them near Deep Blue sea region at (2605, 336)")
AddHelpInfo("Elite Skeletal Warrior","Somebody spotted them near Deep Blue sea region at (2552, 806)")
AddHelpInfo("Great Polliwog","Somebody spotted them near Deep Blue sea region at (1807, 1467)")
AddHelpInfo("Tornado Sea Jelly","Somebody spotted them near Deep Blue sea region at (51, 1492)")
AddHelpInfo("Sawtooth Shark","Somebody spotted them near Deep Blue sea region at (2842, 1158)")
AddHelpInfo("Horrific Snowman","Somebody spotted them near Deep Blue sea region at (3091, 550)")
AddHelpInfo("Horrific Yeti","Somebody spotted them near Deep Blue sea region at (2552, 764)")
AddHelpInfo("Skeletal Archer","Somebody spotted them near Deep Blue sea region at (2204,430)")
AddHelpInfo("Skeletal Warrior","Somebody spotted them near Deep Blue sea region at (2204,430)")
AddHelpInfo("Berserk Electric Sea Jelly","Somebody spotted them near Deep Blue sea region at (51, 1492)")
AddHelpInfo("Tempest Sea Jelly","Somebody spotted them near Deep Blue sea region at (141, 2707)")
AddHelpInfo("Werewolf Archer","Somebody spotted them near Deep Blue sea region at (2632, 764)")
AddHelpInfo("Deadly Werewolf Archer","Somebody spotted them near Deep Blue sea region at (3221, 3246)")
AddHelpInfo("Werewolf Warrior","Somebody spotted them near Deep Blue sea region at (2522, 510)")
AddHelpInfo("Thunder Sea Jelly","Somebody spotted them near Deep Blue sea region at (3442, 1158)")
AddHelpInfo("Sharp Beak","Somebody spotted them near Deep Blue sea region at (798, 488)")
AddHelpInfo("Fragile Snow Doll","Somebody spotted them near Deep Blue sea region at (830, 810)")
AddHelpInfo("Horned Penguin","Somebody spotted them near Magical Ocean region at (835, 308)")
AddHelpInfo("Ferocious Scorpion","Somebody spotted them near Deep Blue sea region at (2337, 506)")
AddHelpInfo("Elk","Somebody spotted them near Magical Ocean region at (835, 308)")
AddHelpInfo("Swift Baby Squid","Somebody spotted them near Deep Blue sea region at (3568, 150)")
AddHelpInfo("Snowy Tortoise","Somebody spotted them near Deep Blue sea region at (2130, 428)")
AddHelpInfo("Ancient Dark Blue Siren","Somebody spotted them near Deep Blue sea region at (1827,2087)")
AddHelpInfo("Ocean Water Dancer","Somebody spotted them near Deep Blue sea region at (1250, 860)")
AddHelpInfo("Dark Blue Siren","Somebody spotted them near Deep Blue sea region at (710, 2052)")
AddHelpInfo("Decaying Fish Bone","Somebody spotted them near Deep Blue sea region at (1740,1160)")
AddHelpInfo("Man Eating Sea Jelly","Somebody spotted them near Deep Blue sea region at (141, 1040)")
AddHelpInfo("Vampiric Polliwog","Somebody spotted them near Deep Blue sea region at (51, 2052)")
AddHelpInfo("Sailor Penguin","Somebody spotted them near Deep Blue sea region at (889, 275)")
AddHelpInfo("Crystalline Dolphin","Somebody spotted them near Deep Blue sea region at (2842, 858)")
AddHelpInfo("Naiad","Somebody spotted them near Deep Blue sea region at (1029, 458)")
AddHelpInfo("Sea Jelly","Somebody spotted them near Deep Blue sea region at (2912, 1463)")
AddHelpInfo("Water Fairy","Somebody spotted them near Magical Ocean region at (2924, 540)")
AddHelpInfo("Battle Tortoise","Somebody spotted them near Deep Blue sea region at (2130, 428)")
AddHelpInfo("Skeleton Fish","Somebody spotted them near Deep Blue sea region at (41, 592)")
AddHelpInfo("Lizardman","Somebody spotted them near Deep Blue sea region at (2532,866)")
AddHelpInfo("War Tortoise","Somebody spotted them near Deep Blue sea region at (852, 708)")
AddHelpInfo("Fallen Naiad","Somebody spotted them near Deep Blue sea region at (852, 708)")
AddHelpInfo("Baby Icy Dragon","Somebody spotted them near Deep Blue sea region at (3400, 2952)")
AddHelpInfo("Baby Squid","Somebody spotted them near Deep Blue sea region at (3268, 150)")
AddHelpInfo("Evil Tribal Shaman","Somebody spotted them near Magical Ocean region at (3400, 3047)")
AddHelpInfo("Evil Blood Polliwog","Somebody spotted them near Deep Blue sea region at (3442, 1158)")
AddHelpInfo("Feral Diamond Dolphin","Somebody spotted them near Magical Ocean region at (1883, 3595)")
AddHelpInfo("Feral Skeleton Fish","Somebody spotted them near Deep Blue sea region at (2842, 1158)")
AddHelpInfo("Snowy Bat","Somebody spotted them near Deep Blue sea region at (713, 338)")
AddHelpInfo("Snowy Shroom","Somebody spotted them near Deep Blue sea region at (885, 518)")
AddHelpInfo("Snowy Mystic Shrub","Somebody spotted them near Deep Blue sea region at (889,288)")
AddHelpInfo("Snowy Wolf","Somebody spotted them near Deep Blue sea region at (930,738)")
AddHelpInfo("Snowy Snail","Somebody spotted them near Deep Blue sea region at (621, 288)")
AddHelpInfo("Snowy Tusk Boar","Somebody spotted them near Deep Blue sea region at (2204, 540)")
AddHelpInfo("Snowman","Somebody spotted them near Deep Blue sea region at (2522, 410)")
AddHelpInfo("Snow Spirit","Somebody spotted them near Deep Blue sea region at (1020, 778)")
AddHelpInfo("Cumbersome Yeti","Somebody spotted them near Deep Blue sea region at (2810, 401)")
AddHelpInfo("Snow Lady","Somebody spotted them near Deep Blue sea region at (853, 592)")
AddHelpInfo("Yeti","Somebody spotted them near Deep Blue sea region at (1403, 632)")
AddHelpInfo("Snowy Bear Cub","Somebody spotted them near Deep Blue sea region at (933, 612)")
AddHelpInfo("Snow Squirt","Somebody spotted them near Deep Blue sea region at (611, 288)")
AddHelpInfo("Snow Squidy","Somebody spotted them near Deep Blue sea region at (1437, 363)")
AddHelpInfo("Blood Polliwog","Somebody spotted them near Deep Blue sea region at (1180, 780)")
AddHelpInfo("Swift Electric Sea Jelly","Somebody spotted them near Deep Blue sea region at (3442, 858)")
AddHelpInfo("Swift Water Dancer","Somebody spotted them near Deep Blue sea region at (2932, 1483)")
AddHelpInfo("Rapid Squid","Somebody spotted them near Deep Blue sea region at (2842, 858)")
AddHelpInfo("Midnight Water Dancer","Somebody spotted them near Deep Blue sea region at (2932, 1483)")
AddHelpInfo("Armored Crab","Somebody spotted them near Deep Blue sea region at (964, 810)")
AddHelpInfo("Wandering Mermaid","Somebody spotted them near Deep Blue sea region at (965, 3384)")
AddHelpInfo("Spiny Fish Bone","Somebody spotted them near Deep Blue sea region at (51, 2052)")
AddHelpInfo("Combat Piglet","Somebody spotted them near Deep Blue sea region at (1403,529)")
AddHelpInfo("Oyster","Somebody spotted them near Deep Blue sea region at (889, 375)")


--掉料
AddHelpInfo("Frozen Grass","Rumored that Snowy Mystic Shrub has a certain drop rate")
AddHelpInfo("Green Grass","Rumored that Mystic Shrub has a certain drop rate")
AddHelpInfo("Sparkling Grass","Rumored that Dry Mystic Shrub has a certain drop rate")
AddHelpInfo("Thorny Thick Skin","Rumored that Melon has a certain drop rate")
AddHelpInfo("Frozen Squid Ink","Rumored that Snow Squirt has a certain drop rate")
AddHelpInfo("Flowery Snail Shell","Rumored that Sleepy Snail has a certain drop rate")
AddHelpInfo("Scorpion Tail","Rumored that Baby Scorpion has a certain drop rate")
AddHelpInfo("Wing","Rumored that Forest Spirit has a certain drop rate")
AddHelpInfo("Octopus Ink","Rumored that Little Squirt has a certain drop rate")
AddHelpInfo("Sweet Smelling Flower","Rumored that Mystic Flower has a certain drop rate")
AddHelpInfo("Cactus Thorn","Rumored that Cactus has a certain drop rate")
AddHelpInfo("Fat Squid Tentacle","Rumored that Snow Squidy has a certain drop rate")
AddHelpInfo("Icy Flower","Rumored that Snowy Mystic Flower has a certain drop rate")
AddHelpInfo("Bee Wing","Rumored that Mini Bee has a certain drop rate")
AddHelpInfo("Octopus Tentacle","Rumored that Little Squidy has a certain drop rate")
AddHelpInfo("Camel Mane","Rumored that Humpy Camel has a certain drop rate")
AddHelpInfo("Snowy Pig Tail","Rumored that Snowy Piglet has a certain drop rate")
AddHelpInfo("Poison Mushroom","Rumored that Greedy Shroom has a certain drop rate")
AddHelpInfo("Broken Antler","Rumored that Little Deer has a certain drop rate")
AddHelpInfo("Grass Tortoise Shell","Rumored that Grass Tortoise has a certain drop rate")
AddHelpInfo("Scorpion Stinger","Rumored that Big Scorpion has a certain drop rate")
AddHelpInfo("Pure Wool","Rumored that Cuddly Lamb has a certain drop rate")
AddHelpInfo("Trumpet Shell","Rumored that Sea Snail has a certain drop rate")
AddHelpInfo("Blue Conch","Rumored that Bubble Clam has a certain drop rate")
AddHelpInfo("Well-Formed Antler","Rumored that Little White Deer has a certain drop rate")
AddHelpInfo("Black Wings","Rumored that Marsh Spirit has a certain drop rate")
AddHelpInfo("Flowery Lizard Skin","Rumored that Hopping Lizard has a certain drop rate")
AddHelpInfo("Pig Tail","Rumored that Piglet has a certain drop rate")
AddHelpInfo("Penguin Pelt","Rumored that Sailor Penguin has a certain drop rate")
AddHelpInfo("Contaminated Water","Rumored that Naiad has a certain drop rate")
AddHelpInfo("Wolf Fang","Rumored that Wolf Cub has a certain drop rate")
AddHelpInfo("Bear Paw","Rumored that Bear Cub has a certain drop rate")
AddHelpInfo("Flowery Conch","Rumored that Oyster has a certain drop rate")
AddHelpInfo("Razor Sharp Beak","Rumored that Sharp Beak has a certain drop rate")
AddHelpInfo("Sharp Cactus Thorn","Rumored that Killer Cactus has a certain drop rate")
AddHelpInfo("Gigantic Antler","Rumored that Elk has a certain drop rate")
AddHelpInfo("Silky Soft Wool","Rumored that Whacky Lamb has a certain drop rate")
AddHelpInfo("Crab Carapace","Rumored that Iron Crab has a certain drop rate")
AddHelpInfo("Concentrated Squid Ink","Rumored that Sailor Squirt has a certain drop rate")
AddHelpInfo("Tough Penguin Pelt","Rumored that Horned Penguin has a certain drop rate")
AddHelpInfo("Slightly Poisonous Thorn","Rumored that Gigantic Melon has a certain drop rate")
AddHelpInfo("Golden Conch Shell","Rumored that Great King Clam has a certain drop rate")
AddHelpInfo("Rigid Crab Carapace","Rumored that Sentry Crab has a certain drop rate")
AddHelpInfo("Bat Wing","Rumored that Snowy Bat has a certain drop rate")
AddHelpInfo("Strong Squid Tentacle","Rumored that Sailor Squidy has a certain drop rate")
AddHelpInfo("Bamboo Shoot","Rumored that Angelic Panda has a certain drop rate")
AddHelpInfo("Strange Branch","Rumored that Phantom Tree has a certain drop rate")
AddHelpInfo("Hypnotic Spore","Rumored that Snowy Shroom has a certain drop rate")
AddHelpInfo("Chilling Snail Shell","Rumored that Snowy Snail has a certain drop rate")
AddHelpInfo("Poisonous Mushroom","Rumored that Killer Shroom has a certain drop rate")
AddHelpInfo("Lock Pick","Rumored that Sand Brigand has a certain drop rate")
AddHelpInfo("Razor Wolf Fang","Rumored that Starving Wolf has a certain drop rate")
AddHelpInfo("Fake Documentation","Rumored that Smuggler has a certain drop rate")
AddHelpInfo("Soldier Bee Wing","Rumored that Barbaric Bee has a certain drop rate")
AddHelpInfo("Snowball","Rumored that Naive Snow Doll has a certain drop rate")
AddHelpInfo("Black Feather","Rumored that Owlie has a certain drop rate")
AddHelpInfo("Coarse Tortoise Shell","Rumored that Sandy Tortoise has a certain drop rate")
AddHelpInfo("Boar Spine","Rumored that Tusk Battle Boar has a certain drop rate")
AddHelpInfo("Wind Mirror","Rumored that Sand Bandit has a certain drop rate")
AddHelpInfo("Hard Trumpet Shell","Rumored that Hard Crust Snail has a certain drop rate")
AddHelpInfo("Damaged Puck","Rumored that Snowy Bear Cub has a certain drop rate")
AddHelpInfo("Kangaroo Pouch","Rumored that Rookie Boxeroo has a certain drop rate")
AddHelpInfo("Small Tooth","Rumored that Air Porky has a certain drop rate")
AddHelpInfo("Poisonous Spore","Rumored that Sandy Shroom has a certain drop rate")
AddHelpInfo("Mud Cake","Rumored that Mudman has a certain drop rate")
AddHelpInfo("Mighty Wolf Claw","Rumored that Snowy Wolf has a certain drop rate")
AddHelpInfo("Bandit Bandana","Rumored that Bandit has a certain drop rate")
AddHelpInfo("Ice Crystal","Rumored that Snow Lady has a certain drop rate")
AddHelpInfo("Low Grade Antler","Rumored that Meadow Deer has a certain drop rate")
AddHelpInfo("Bandit Sash","Rumored that Bandit Leader - Adder has a certain drop rate")
AddHelpInfo("Stramonium Flower","Rumored that Stramonium has a certain drop rate")
AddHelpInfo("Giant Wolf Fang","Rumored that Feral Wolf has a certain drop rate")
AddHelpInfo("Smelly Water","Rumored that Fallen Naiad has a certain drop rate")
AddHelpInfo("Sticky Spider Legs","Rumored that Man Eating Spider has a certain drop rate")
AddHelpInfo("Unusable Crab Feet","Rumored that Armored Crab has a certain drop rate")
AddHelpInfo("Snowy Trumpet Shell","Rumored that Northern Snail has a certain drop rate")
AddHelpInfo("Gigantic Tortoise Shell","Rumored that War Tortoise has a certain drop rate")
AddHelpInfo("Half Eaten Foilage","Rumored that Mature Grass Tortoise has a certain drop rate")
AddHelpInfo("Snow Spirit Wings","Rumored that Snow Spirit has a certain drop rate")
AddHelpInfo("Cracked Iron Sword","Rumored that Sand Bandit Leader - Garet has a certain drop rate")
AddHelpInfo("Rugged Pig Tail","Rumored that Mad Boar has a certain drop rate")
AddHelpInfo("Blue Snowball","Rumored that Fragile Snow Doll has a certain drop rate")
AddHelpInfo("Knight Attest","Rumored that Sand Raider has a certain drop rate")
AddHelpInfo("Steel Pig Tooth","Rumored that Combat Piglet has a certain drop rate")
AddHelpInfo("Huge Crab Pincers","Rumored that Armored King Crab has a certain drop rate")
AddHelpInfo("Little Devil Wings","Rumored that Vampire Bat has a certain drop rate")
AddHelpInfo("Yeti Chest Hair","Rumored that Yeti has a certain drop rate")
AddHelpInfo("Rigid Deer Hoof","Rumored that Grassland Elk has a certain drop rate")
AddHelpInfo("Burly Lizard Skin","Rumored that Lizard King has a certain drop rate")
AddHelpInfo("Metal Earring","Rumored that Atrocious Yeti King has a certain drop rate")
AddHelpInfo("Ruffled Wolf Tail","Rumored that Grassland Wolf has a certain drop rate")
AddHelpInfo("Red Snowball","Rumored that Playful Snow Doll has a certain drop rate")
AddHelpInfo("Mole Claw","Rumored that Miner Mole has a certain drop rate")
AddHelpInfo("King-Sized Kangaroo Pouch","Rumored that Berserk Boxeroo has a certain drop rate")
AddHelpInfo("Cracked Tortoise Shell","Rumored that Battle Tortoise has a certain drop rate")
AddHelpInfo("Cumbersome Carapace","Rumored that Slowpoke Snail has a certain drop rate")
AddHelpInfo("Iron Hook","Rumored that Captain Fickle has a certain drop rate")
AddHelpInfo("Old Quiver","Rumored that Skeletal Archer has a certain drop rate")
AddHelpInfo("Sticky Mud Cake","Rumored that Mud Monster has a certain drop rate")
AddHelpInfo("Snowy White Plume","Rumored that White Owlie has a certain drop rate")
AddHelpInfo("Blunt Nail","Rumored that Snowy Tortoise has a certain drop rate")
AddHelpInfo("Mangled Sheep Horn","Rumored that Crazy Sheep has a certain drop rate")
AddHelpInfo("Dangerous Sharp Claw","Rumored that Stinging Beak has a certain drop rate")
AddHelpInfo("Solid Tortoise Shell","Rumored that Fearsome Tortoise has a certain drop rate")
AddHelpInfo("Solid Bear Paw","Rumored that Polar Bear has a certain drop rate")
AddHelpInfo("Broken Ninja Sword","Rumored that Ninja Mole has a certain drop rate")
AddHelpInfo("Deadly Poisonous Stinger","Rumored that Ferocious Scorpion has a certain drop rate")
AddHelpInfo("Spikey Spike","Rumored that Snowy Tusk Boar has a certain drop rate")
AddHelpInfo("Lizard Tail","Rumored that Thickskin Lizard has a certain drop rate")
AddHelpInfo("Solid Rock","Rumored that Rock Golem has a certain drop rate")
AddHelpInfo("Rusty Katana","Rumored that Skeletal Warrior has a certain drop rate")
AddHelpInfo("Glistening Shrub","Rumored that Seaweed has a certain drop rate")
AddHelpInfo("Transparent Sea Jelly Skin","Rumored that Sea Jelly has a certain drop rate")
AddHelpInfo("Speckled Fish Scale","Rumored that Skeleton Fish has a certain drop rate")
AddHelpInfo("Squid Ink","Rumored that Baby Squid has a certain drop rate")
AddHelpInfo("Arabic Bandana","Rumored that Water Dancer has a certain drop rate")
AddHelpInfo("Glittery Sea Jelly Skin","Rumored that Electric Sea Jelly has a certain drop rate")
AddHelpInfo("Blood Red Polliwog skin","Rumored that Blood Polliwog has a certain drop rate")
AddHelpInfo("Heart of Merman","Rumored that Mermaid has a certain drop rate")
AddHelpInfo("Slimy Sea Jelly Skin","Rumored that Tempest Sea Jelly has a certain drop rate")
AddHelpInfo("Glittery Dolphin Skin","Rumored that Ruby Dolphin has a certain drop rate")
AddHelpInfo("Fish Bone","Rumored that Fish Bone has a certain drop rate")
AddHelpInfo("Black Polliwog Skin","Rumored that Great Polliwog has a certain drop rate")
AddHelpInfo("Broken Long Spear","Rumored that Azure Siren has a certain drop rate")
AddHelpInfo("Shark Tooth","Rumored that Sawtooth Shark has a certain drop rate")
AddHelpInfo("Slimy Dolphin Skin","Rumored that Crystalline Dolphin has a certain drop rate")
AddHelpInfo("Rusty Long Spear","Rumored that Crimson Siren has a certain drop rate")
AddHelpInfo("Agate","Rumored that Mermaid Queen has a certain drop rate")
AddHelpInfo("Ancient Scroll","Rumored that Siren Queen has a certain drop rate")
AddHelpInfo("","Rumored that there is a certain drop rate")
AddHelpInfo("Drop 1","Rumored that monsters has a certain drop rate")
AddHelpInfo("Giant Wolf Fang","Rumored that Wolf has a certain drop rate")
AddHelpInfo("Snowman's Earring","Rumored that Cumbersome Snowman has a certain drop rate")
AddHelpInfo("Broken Werewolf Warrior Emblem","Rumored that Werewolf Warrior has a certain drop rate")
AddHelpInfo("Thorny Stramonium Flower","Rumored that Spiky Stramonium has a certain drop rate")
AddHelpInfo("Tribal Feather","Rumored that Tribal Villager has a certain drop rate")
AddHelpInfo("Giant Earring","Rumored that Snowman has a certain drop rate")
AddHelpInfo("Steel Snail Shell","Rumored that Steel-shell Snail has a certain drop rate")
AddHelpInfo("Cracked Snowman Necklace","Rumored that Cumbersome Yeti has a certain drop rate")
AddHelpInfo("Unyielding Bow","Rumored that Undead Archer has a certain drop rate")
AddHelpInfo("Giant Necklace","Rumored that Snow Yeti has a certain drop rate")
AddHelpInfo("Pumpkin Head","Rumored that Pumpkin Knight has a certain drop rate")
AddHelpInfo("Tribal Knife","Rumored that Tribal Warrior has a certain drop rate")
AddHelpInfo("Refined Arrow Quiver","Rumored that Elite Skeletal Archer has a certain drop rate")
AddHelpInfo("Frozen Bone Fragment","Rumored that Infant Icy Dragon has a certain drop rate")
AddHelpInfo("Gravel Crab Pincer","Rumored that Sand Crab has a certain drop rate")
AddHelpInfo("Dried Wood","Rumored that Treant has a certain drop rate")
AddHelpInfo("Dark Mud Cake","Rumored that Dark Mud Monster has a certain drop rate")
AddHelpInfo("Huge Bear Paw","Rumored that Great Polar Bear has a certain drop rate")
AddHelpInfo("Water Crystal","Rumored that Water Fairy has a certain drop rate")
AddHelpInfo("Sparkling Snowman Earring","Rumored that Horrific Snowman has a certain drop rate")
AddHelpInfo("Chipped Werewolf Iron Claw","Rumored that Werewolf Archer has a certain drop rate")
AddHelpInfo("Indestructible Rock","Rumored that Sturdy Rock Golem has a certain drop rate")
AddHelpInfo("Bloodied Wolf Fang","Rumored that Frenzied Wolf has a certain drop rate")
AddHelpInfo("Sparkling Snowman Necklace","Rumored that Horrific Yeti has a certain drop rate")
AddHelpInfo("Sakura Sailor's Emblem","Rumored that Sakura Pirate Sailor has a certain drop rate")
AddHelpInfo("Broken Katana","Rumored that Elite Skeletal Warrior has a certain drop rate")
AddHelpInfo("Sakura Fighter's Emblem","Rumored that Sakura Pirate Fighter has a certain drop rate")
AddHelpInfo("Sakura Militia's Emblem","Rumored that Sakura Pirate Militia has a certain drop rate")
AddHelpInfo("Unyielding Greatsword","Rumored that Undead Warrior has a certain drop rate")
AddHelpInfo("Werewolf Warrior Emblem","Rumored that Elite Werewolf Warrior has a certain drop rate")
AddHelpInfo("Iron Shroud","Rumored that Iron Mummy has a certain drop rate")
AddHelpInfo("Gigantic Stramonium Flower","Rumored that Huge Spiky Stramonium has a certain drop rate")
AddHelpInfo("Steel Shroud","Rumored that Steel Mummy has a certain drop rate")
AddHelpInfo("Tribal Long Spear","Rumored that Tribal Shaman has a certain drop rate")
AddHelpInfo("Lizardman Belt","Rumored that Lizardman has a certain drop rate")
AddHelpInfo("Beautiful Tribal Feathers","Rumored that Agile Tribal Villager has a certain drop rate")
AddHelpInfo("Angel Halo","Rumored that Guardian Angel has a certain drop rate")
AddHelpInfo("Fallen Greatsword","Rumored that Vicious Undead Warrior has a certain drop rate")
AddHelpInfo("Royal Emblem","Rumored that Palace Guard has a certain drop rate")
AddHelpInfo("Northern Sailor's Emblem","Rumored that Northern Pirate Sailor has a certain drop rate")
AddHelpInfo("Northern Fighter's Emblem","Rumored that Northern Pirate Fighter has a certain drop rate")
AddHelpInfo("Special Quiver","Rumored that Deadly Skeletal Archer has a certain drop rate")
AddHelpInfo("Northern Militia's Emblem","Rumored that Northern Pirate Militia has a certain drop rate")
AddHelpInfo("Heart of Nature","Rumored that Forest Hunter has a certain drop rate")
AddHelpInfo("Wornout Katana","Rumored that Skeletal Warrior Leader has a certain drop rate")
AddHelpInfo("Shroud","Rumored that Cursed Corpse has a certain drop rate")
AddHelpInfo("Dark Skeleton","Rumored that Bloodthirsty Hunter has a certain drop rate")
AddHelpInfo("Broken Terra Pickaxe","Rumored that Terra Soldier has a certain drop rate")
AddHelpInfo("Fake Navy Documentation","Rumored that Navy Rifleman has a certain drop rate")
AddHelpInfo("Wild Shrub","Rumored that Wild Seaweed has a certain drop rate")
AddHelpInfo("Floating Shrub","Rumored that Floating Seaweed has a certain drop rate")
AddHelpInfo("Mouldy Grass","Rumored that Icky Seaweed has a certain drop rate")
AddHelpInfo("Cursed Shrub","Rumored that Cursed Seaweed has a certain drop rate")
AddHelpInfo("White Sea Jelly Skin","Rumored that White Cap Sea Jelly has a certain drop rate")
AddHelpInfo("Raw Sea Jelly Skin","Rumored that Man Eating Sea Jelly has a certain drop rate")
AddHelpInfo("Black Ink","Rumored that Blackarrow Squid has a certain drop rate")
AddHelpInfo("Slippery Scale","Rumored that Swift Skeleton Fish has a certain drop rate")
AddHelpInfo("Black Scale","Rumored that Tanned Skeleton Fish has a certain drop rate")
AddHelpInfo("Dense Squid Ink","Rumored that Sluggish Squid has a certain drop rate")
AddHelpInfo("Refined Arabian Bandana","Rumored that Ocean Water Dancer has a certain drop rate")
AddHelpInfo("Dark Ink","Rumored that Vicious Baby Squid has a certain drop rate")
AddHelpInfo("Evil Arabic Bandana","Rumored that Evil Water Dancer has a certain drop rate")
AddHelpInfo("Poisonous Sea Jelly Skin","Rumored that Poisonous Sea Jelly has a certain drop rate")
AddHelpInfo("Lacerated Sea Jelly Skin","Rumored that Raging Sea Jelly has a certain drop rate")
AddHelpInfo("Belched Ink","Rumored that Blackout Squid has a certain drop rate")
AddHelpInfo("Salty Octopus Ink","Rumored that Octopus has a certain drop rate")
AddHelpInfo("Stale Octopus Ink","Rumored that Chameleon Squid has a certain drop rate")
AddHelpInfo("Rotten Fish Scale","Rumored that Decaying Fish Bone has a certain drop rate")
AddHelpInfo("Evil Scale","Rumored that Evil Skeleton Fish has a certain drop rate")
AddHelpInfo("Diluted Squid Ink","Rumored that Swift Baby Squid has a certain drop rate")
AddHelpInfo("Nasal Squid Ink","Rumored that Rapid Squid has a certain drop rate")
AddHelpInfo("Dark Arabic Bandana","Rumored that Midnight Water Dancer has a certain drop rate")
AddHelpInfo("High Quality Arabic Bandana","Rumored that Swift Water Dancer has a certain drop rate")
AddHelpInfo("Massive Speckled Fish Scale","Rumored that Feral Skeleton Fish has a certain drop rate")
AddHelpInfo("Charged Sea Jelly Skin","Rumored that Thunder Sea Jelly has a certain drop rate")
AddHelpInfo("Electrical Jelly Skin","Rumored that Shocking Sea Jelly has a certain drop rate")
AddHelpInfo("Evil Polliwog Skin","Rumored that Evil Blood Polliwog has a certain drop rate")
AddHelpInfo("Shining Dolphin Tail","Rumored that Swift Electric Sea Jelly has a certain drop rate")
AddHelpInfo("Massive Polliwog Skin","Rumored that Feral Blood Polliwog has a certain drop rate")
AddHelpInfo("Translucent Polliwog Fish Tail","Rumored that Stealth Blood Polliwog has a certain drop rate")
AddHelpInfo("Depraved Merman Heart","Rumored that Vicious Mermaid has a certain drop rate")
AddHelpInfo("Broken Jack's Chest","Rumored that Jack the Pirate's Support Ship has a certain drop rate")
AddHelpInfo("Broken Jack's Ship Bow","Rumored that Jack the Pirate's Warship has a certain drop rate")
AddHelpInfo("Perfect Mermaid Heart","Rumored that Wandering Mermaid has a certain drop rate")
AddHelpInfo("Shadow Fish Heart","Rumored that Shadow Mermaid has a certain drop rate")
AddHelpInfo("Huge Shark Sawtooth","Rumored that Old Sawtooth Shark has a certain drop rate")
AddHelpInfo("White Shark Tooth","Rumored that White Finned Shark has a certain drop rate")
AddHelpInfo("Jack the Pirate's Direction Chart","Rumored that Jack the Pirate's Command Ship has a certain drop rate")
AddHelpInfo("Great Shark Tooth","Rumored that Spearhead Shark has a certain drop rate")
AddHelpInfo("Razor Sharp Shark Tooth","Rumored that Black Finned Shark has a certain drop rate")
AddHelpInfo("Broken Sakura Chest","Rumored that Sakura 13 Support Ship has a certain drop rate")
AddHelpInfo("Large Shiny Sea Jelly Skin","Rumored that Raging Electric Sea Jelly has a certain drop rate")
AddHelpInfo("Broken Sakura Ship Bow","Rumored that Sakura 13 Warship has a certain drop rate")
AddHelpInfo("Bloody Polliwog Skin","Rumored that Vampiric Polliwog has a certain drop rate")
AddHelpInfo("Dried Sea Jelly Skin","Rumored that Tempest Sea Jelly has a certain drop rate")
AddHelpInfo("Keen Shark Tooth","Rumored that Silk Shark has a certain drop rate")
AddHelpInfo("Glimmering Dolphin Tail","Rumored that Topaz Dolphin has a certain drop rate")
AddHelpInfo("Dry Dolphin Skin","Rumored that Hurricane Sea Jelly has a certain drop rate")
AddHelpInfo("Mature Dolphin Tail","Rumored that Mature Ruby Dolphin has a certain drop rate")
AddHelpInfo("Sakira Pirate Direction Chart","Rumored that Sakura 13 Pirate Command Ship has a certain drop rate")
AddHelpInfo("Fascia Fish Bone","Rumored that Spiny Fish Bone has a certain drop rate")
AddHelpInfo("Broken Northen Chest","Rumored that Northern Pirate Support Ship has a certain drop rate")
AddHelpInfo("Thick Fish Bone","Rumored that Hungry Fish Bone has a certain drop rate")
AddHelpInfo("Broken Northen Ship Bow","Rumored that Northern Pirate Warship has a certain drop rate")
AddHelpInfo("Hugh Rock Fragment","Rumored that Stone Golem has a certain drop rate")
AddHelpInfo("Arcane Metal","Rumored that Iron Golem has a certain drop rate")
AddHelpInfo("Damaged Lizardman Belt","Rumored that Lizard Warrior has a certain drop rate")
AddHelpInfo("Small Mysterious Branch","Rumored that Small Treant has a certain drop rate")
AddHelpInfo("Giant Lizard Tongue","Rumored that Giant Lizard has a certain drop rate")
AddHelpInfo("Long Hair Crab Pincer","Rumored that Long Hair Crab has a certain drop rate")
AddHelpInfo("Cursed Shroud","Rumored that Horrific Cursed Corpse has a certain drop rate")
AddHelpInfo("Frightful Pumpkin Head","Rumored that Vicious Pumpkin Knight has a certain drop rate")
AddHelpInfo("Chimera Horn","Rumored that Chimera has a certain drop rate")
AddHelpInfo("Razor Tribal Knife","Rumored that Elite Tribal Warrior has a certain drop rate")
AddHelpInfo("Dried Splintered Wood","Rumored that Treant Terror has a certain drop rate")
AddHelpInfo("Rusty Terra Battleaxe","Rumored that Terra Warrior has a certain drop rate")
AddHelpInfo("Piece of Icy Dragon Bone","Rumored that Baby Icy Dragon has a certain drop rate")
AddHelpInfo("Werewolf Iron Claw","Rumored that Elite Werewolf Archer has a certain drop rate")
AddHelpInfo("Fine Exquisite Feather","Rumored that Mad Tribal Villager has a certain drop rate")
AddHelpInfo("Evil Greatsword","Rumored that Evil Undead Warrior has a certain drop rate")
AddHelpInfo("Ghastly Pumpkin Head","Rumored that Evil Pumpkin Knight has a certain drop rate")
AddHelpInfo("Werewolf Warrior Leader's Insignia","Rumored that Werewolf Warrior Leader has a certain drop rate")
AddHelpInfo("Broken Shadow Hunter Short Bow","Rumored that Shadow Hunter has a certain drop rate")
AddHelpInfo("Royal Bodyguard Emblem","Rumored that Palace Guard has a certain drop rate")
AddHelpInfo("Mysterious Branch","Rumored that Lumbering Treant has a certain drop rate")
AddHelpInfo("Cursed Water Crystal","Rumored that Cursed Water Fairy has a certain drop rate")
AddHelpInfo("Broken Angel Halo","Rumored that Corrupted Guardian Angel has a certain drop rate")
AddHelpInfo("Pointed Tribal Long Spear","Rumored that Mad Tribal Witchdoctor has a certain drop rate")
AddHelpInfo("Iron Casted Lizardman Belt","Rumored that Frenzied Lizardman has a certain drop rate")
AddHelpInfo("Nimble Heart of Nature","Rumored that Nimble Forest Hunter has a certain drop rate")
AddHelpInfo("Torn White Bobcat Wing","Rumored that White Bobcat has a certain drop rate")
AddHelpInfo("Rusty Terra Earrings","Rumored that Terra Elder has a certain drop rate")
AddHelpInfo("Terra Spanner","Rumored that Terra Artificer has a certain drop rate")
AddHelpInfo("Damaged Terra Battleaxe","Rumored that Terra Captain has a certain drop rate")
AddHelpInfo("Dark Bloody Carcass","Rumored that Nimble Shadow Hunter has a certain drop rate")
AddHelpInfo("Terra Pickaxe","Rumored that Terra Soldier Leader has a certain drop rate")
AddHelpInfo("Tough Lizardman Necklace","Rumored that Elite Lizardman Warrior has a certain drop rate")
AddHelpInfo("Lizardman Leader Belt","Rumored that Lizard Warrior Leader has a certain drop rate")
AddHelpInfo("Heavy Terra Battleaxe","Rumored that Elite Terra Warrior has a certain drop rate")
AddHelpInfo("Terra Captain Battleaxe","Rumored that Terra Warrior Leader has a certain drop rate")
AddHelpInfo("Torn Black Bobcat Wing","Rumored that Black Bobcat has a certain drop rate")
AddHelpInfo("Cracked Terra Earring","Rumored that Vicious Grassland Elder has a certain drop rate")
AddHelpInfo("King-Size Spanner","Rumored that Terra Artificer Leader has a certain drop rate")
AddHelpInfo("Broken Hunter Bow","Rumored that Elite Shadow Hunter has a certain drop rate")
AddHelpInfo("White Bobcat Wing","Rumored that Feral White Bobcat has a certain drop rate")
AddHelpInfo("Gigantic Werewolf Iron Claw","Rumored that Deadly Werewolf Archer has a certain drop rate")
AddHelpInfo("Black Bobcat Wing","Rumored that Feral Black Bobcat has a certain drop rate")
AddHelpInfo("Lion Wing","Rumored that Frost Chimera has a certain drop rate")
AddHelpInfo("Corrupted Angel Halo","Rumored that Evil Guardian Angel has a certain drop rate")
AddHelpInfo("Cursed White Bobcat Wing","Rumored that Cursed White Bobcat has a certain drop rate")
AddHelpInfo("Evil Tribal Long Spear","Rumored that Evil Tribal Shaman has a certain drop rate")
AddHelpInfo("Sparkling Lizardman Belt","Rumored that Frantic Lizardman has a certain drop rate")
AddHelpInfo("Gloomy Heart of the Forest","Rumored that Ruthless Forest Hunter has a certain drop rate")
AddHelpInfo("Cursed Black Bobcat Wing","Rumored that Cursed Black Bobcat has a certain drop rate")
AddHelpInfo("Robot Clamp","Rumored that Relic Guard has a certain drop rate")
AddHelpInfo("Bloodied Carcass","Rumored that Ruthless Shadow Hunter has a certain drop rate")
AddHelpInfo("Scythe of Anubis","Rumored that Anubis has a certain drop rate")
AddHelpInfo("Robot Wheel","Rumored that Relic Protector has a certain drop rate")
AddHelpInfo("Ancient Incantation","Rumored that Dharma Pharaoh has a certain drop rate")
AddHelpInfo("Beardy Sailor's Emblem","Rumored that Beardy Pirate Sailor has a certain drop rate")
AddHelpInfo("Beardy Fighter's Emblem","Rumored that Beardy Pirate Fighter has a certain drop rate")
AddHelpInfo("Beardy Militia's Emblem","Rumored that Beardy Pirate Militia has a certain drop rate")
AddHelpInfo("Rotten Fish Bone","Rumored that Decaying Fish Bone has a certain drop rate")
AddHelpInfo("Rigid Polliwog Skin","Rumored that Big Eyed Polliwog has a certain drop rate")
AddHelpInfo("Possessed Polliwog Skin","Rumored that Evil Great Polliwog has a certain drop rate")
AddHelpInfo("Beefy Polliwog Tail","Rumored that Great Feral Polliwog has a certain drop rate")
AddHelpInfo("Northern Pirate Direction Chart","Rumored that Northern Pirate Command Ship has a certain drop rate")
AddHelpInfo("Shining Sea Jelly Skin","Rumored that Swift Cyclonic Sea Jelly has a certain drop rate")
AddHelpInfo("Cursed Merman Heart","Rumored that Cursed Mermaid has a certain drop rate")
AddHelpInfo("Large Slimy Sea Jelly Skin","Rumored that Raging Cyclonic Sea Jelly has a certain drop rate")
AddHelpInfo("Ancient Dolphin Tail","Rumored that Old Ruby Dolphin has a certain drop rate")
AddHelpInfo("Huge Fish Bone","Rumored that Feral Fish Bone has a certain drop rate")
AddHelpInfo("Large Polliwog Skin","Rumored that Great Prowling Polliwog has a certain drop rate")
AddHelpInfo("Strong Dolphin Tail","Rumored that Feral Ruby Dolphin has a certain drop rate")
AddHelpInfo("Rusty Siren Lance","Rumored that Bewitching Siren has a certain drop rate")
AddHelpInfo("Purple Dolphin Tale","Rumored that Amethyst Dolphin has a certain drop rate")
AddHelpInfo("Enlightened Dolphin Tail","Rumored that Old Diamond Dolphin has a certain drop rate")
AddHelpInfo("Rusty Dark Lance","Rumored that Dark Blue Siren has a certain drop rate")
AddHelpInfo("Rusty Siren Bow","Rumored that Siren Archer has a certain drop rate")
AddHelpInfo("Red Beardy's Chest","Rumored that Beardy Pirate Support Ship has a certain drop rate")
AddHelpInfo("Red Beard","Rumored that Beardy Pirate Warship has a certain drop rate")
AddHelpInfo("Glaring Dolphin Tail","Rumored that Feral Diamond Dolphin has a certain drop rate")
AddHelpInfo("Rusty Sharp Lance","Rumored that Frenzied Siren has a certain drop rate")
AddHelpInfo("Broken Mermaid Necklace","Rumored that Berserk Mermaid Protector has a certain drop rate")
AddHelpInfo("Broken Siren Ornament","Rumored that Berserk Siren Guard has a certain drop rate")
AddHelpInfo("Ancient Lance","Rumored that Ancient Siren has a certain drop rate")
AddHelpInfo("Beardy Pirate Direction Chart","Rumored that Beardy Pirate Command Ship has a certain drop rate")
AddHelpInfo("Ancient Bow","Rumored that Ancient Siren Archer has a certain drop rate")
AddHelpInfo("Dyed Mermaid Necklance","Rumored that Tanned Mermaid Protector has a certain drop rate")
AddHelpInfo("Dyed Siren Ornament","Rumored that Tanned Siren Guard has a certain drop rate")
AddHelpInfo("Broken Mermaid Jeweled Necklace","Rumored that Horrific Mermaid Protector has a certain drop rate")
AddHelpInfo("Broken Siren Jeweled Ornament","Rumored that Horrific Siren Guard has a certain drop rate")
AddHelpInfo("Evil Spear","Rumored that Feral Siren has a certain drop rate")
AddHelpInfo("Shadow Spear","Rumored that Shadow Siren has a certain drop rate")
AddHelpInfo("Ancient Hag Spear","Rumored that Ancient Bewitching Siren has a certain drop rate")
AddHelpInfo("Ancient Dark Blue Long Spear","Rumored that Ancient Dark Blue Siren has a certain drop rate")
AddHelpInfo("Ancient Merman Necklace","Rumored that Ancient Mermaid Protector has a certain drop rate")
AddHelpInfo("Ancient Siren Ornaments","Rumored that Ancient Siren Guard has a certain drop rate")
AddHelpInfo("Jack's Sailor Emblem","Rumored that Jack the Pirate's Sailor has a certain drop rate")
AddHelpInfo("Jack's Fighter Emblem","Rumored that Jack the Pirate's Fighter has a certain drop rate")
AddHelpInfo("Jack's Militia Emblem","Rumored that Jack the Pirate's Militia has a certain drop rate")
AddHelpInfo("Cavalier Insignia","Rumored that Cavalier has a certain drop rate")
AddHelpInfo("Stone of Oath","Rumored that Jack - Black Sail has a certain drop rate")
AddHelpInfo("Frozen Root","Rumored that Snowy Mystic Shrub has a certain drop rate")
AddHelpInfo("Root","Rumored that Mystic Shrub has a certain drop rate")
AddHelpInfo("Ancient Root","Rumored that Dry Mystic Shrub has a certain drop rate")
AddHelpInfo("Melon Tuber","Rumored that Melon has a certain drop rate")
AddHelpInfo("White Squirt Bandana","Rumored that Snow Squirt has a certain drop rate")
AddHelpInfo("Snail Feeler","Rumored that Sleepy Snail has a certain drop rate")
AddHelpInfo("Scorpion Carapace","Rumored that Baby Scorpion has a certain drop rate")
AddHelpInfo("Green Scale","Rumored that Forest Spirit has a certain drop rate")
AddHelpInfo("Squirt Handkerchief","Rumored that Little Squirt has a certain drop rate")
AddHelpInfo("Fresh Flower Petal","Rumored that Mystic Flower has a certain drop rate")
AddHelpInfo("Cacus Tuber","Rumored that Cactus has a certain drop rate")
AddHelpInfo("White Squidy Cap","Rumored that Snow Squidy has a certain drop rate")
AddHelpInfo("Frozen Flower Petal","Rumored that Snowy Mystic Flower has a certain drop rate")
AddHelpInfo("Bee Antenna","Rumored that Mini Bee has a certain drop rate")
AddHelpInfo("Squidy Cap","Rumored that Little Squidy has a certain drop rate")
AddHelpInfo("Camel Eyelash","Rumored that Humpy Camel has a certain drop rate")
AddHelpInfo("Furry Pig Mane","Rumored that Snowy Piglet has a certain drop rate")
AddHelpInfo("Fungus Spore","Rumored that Greedy Shroom has a certain drop rate")
AddHelpInfo("Soft Deer Skin","Rumored that Little Deer has a certain drop rate")
AddHelpInfo("Dark Tortoise Bones","Rumored that Grass Tortoise has a certain drop rate")
AddHelpInfo("Rigid Scorpion Carapace","Rumored that Big Scorpion has a certain drop rate")
AddHelpInfo("Short Goat Horn","Rumored that Cuddly Lamb has a certain drop rate")
AddHelpInfo("Fresh Whelk Meat","Rumored that Sea Snail has a certain drop rate")
AddHelpInfo("Small Conch Fragment","Rumored that Bubble Clam has a certain drop rate")
AddHelpInfo("Thick Deer Skin","Rumored that Little White Deer has a certain drop rate")
AddHelpInfo("Black Scale","Rumored that Marsh Spirit has a certain drop rate")
AddHelpInfo("Long Lizard Tongue","Rumored that Hopping Lizard has a certain drop rate")
AddHelpInfo("Soft Pig Mane","Rumored that Piglet has a certain drop rate")
AddHelpInfo("Webbed Penguin Feet","Rumored that Sailor Penguin has a certain drop rate")
AddHelpInfo("Heart of Naiad","Rumored that Naiad has a certain drop rate")
AddHelpInfo("Wolf Claw","Rumored that Wolf Cub has a certain drop rate")
AddHelpInfo("Fermented Honey","Rumored that Bear Cub has a certain drop rate")
AddHelpInfo("Great Conch Fragment","Rumored that Oyster has a certain drop rate")
AddHelpInfo("Kingfisher Feather","Rumored that Sharp Beak has a certain drop rate")
AddHelpInfo("Large Cactus Tuber","Rumored that Killer Cactus has a certain drop rate")
AddHelpInfo("Tough Deer Skin","Rumored that Elk has a certain drop rate")
AddHelpInfo("Pointed Goat Horn","Rumored that Whacky Lamb has a certain drop rate")
AddHelpInfo("Crab Pincer","Rumored that Iron Crab has a certain drop rate")
AddHelpInfo("Squirt Handkerchief","Rumored that Sailor Squirt has a certain drop rate")
AddHelpInfo("Strong Penguin Feet","Rumored that Horned Penguin has a certain drop rate")
AddHelpInfo("Bitter Fruit","Rumored that Gigantic Melon has a certain drop rate")
AddHelpInfo("Crown","Rumored that Great King Clam has a certain drop rate")
AddHelpInfo("Razer Sharp Pincers","Rumored that Sentry Crab has a certain drop rate")
AddHelpInfo("Bat Fangs","Rumored that Snowy Bat has a certain drop rate")
AddHelpInfo("Squidy Cap","Rumored that Sailor Squidy has a certain drop rate")
AddHelpInfo("Bamboo Leaf","Rumored that Angelic Panda has a certain drop rate")
AddHelpInfo("Phantom Tree Branch","Rumored that Phantom Tree has a certain drop rate")
AddHelpInfo("Edible Mushroom","Rumored that Snowy Shroom has a certain drop rate")
AddHelpInfo("Frozen Snail Feeler","Rumored that Snowy Snail has a certain drop rate")
AddHelpInfo("Poisonous Fungus Spore","Rumored that Killer Shroom has a certain drop rate")
AddHelpInfo("Master Key","Rumored that Sand Brigand has a certain drop rate")
AddHelpInfo("Razor Wolf Claw","Rumored that Starving Wolf has a certain drop rate")
AddHelpInfo("Mystic Pen Head","Rumored that Smuggler has a certain drop rate")
AddHelpInfo("Bee Ration","Rumored that Barbaric Bee has a certain drop rate")
AddHelpInfo("Glacier Heart","Rumored that Naive Snow Doll has a certain drop rate")
AddHelpInfo("Owl Talon","Rumored that Owlie has a certain drop rate")
AddHelpInfo("Desert Seed","Rumored that Sandy Tortoise has a certain drop rate")
AddHelpInfo("Short Boar Tail","Rumored that Tusk Battle Boar has a certain drop rate")
AddHelpInfo("Torn Pouch","Rumored that Sand Bandit has a certain drop rate")
AddHelpInfo("Inedible Conch Meat","Rumored that Hard Crust Snail has a certain drop rate")
AddHelpInfo("Snowy Fluff","Rumored that Snowy Bear Cub has a certain drop rate")
AddHelpInfo("Boxing Gloves","Rumored that Rookie Boxeroo has a certain drop rate")
AddHelpInfo("Unusual Satchet","Rumored that Air Porky has a certain drop rate")
AddHelpInfo("Umbrella Mushroom","Rumored that Sandy Shroom has a certain drop rate")
AddHelpInfo("Polluted Mud","Rumored that Mudman has a certain drop rate")
AddHelpInfo("High Quality Wolf Pelt","Rumored that Snowy Wolf has a certain drop rate")
AddHelpInfo("Bandit Pass","Rumored that Bandit has a certain drop rate")
AddHelpInfo("Perfect Snowflake","Rumored that Snow Lady has a certain drop rate")
AddHelpInfo("Thin Deer Skin","Rumored that Meadow Deer has a certain drop rate")
AddHelpInfo("Spikey Cuffs","Rumored that Bandit Leader - Adder has a certain drop rate")
AddHelpInfo("Stramonium Sharp Spike","Rumored that Stramonium has a certain drop rate")
AddHelpInfo("Huge Wolf Claw","Rumored that Feral Wolf has a certain drop rate")
AddHelpInfo("Broken Heart of Naiad","Rumored that Fallen Naiad has a certain drop rate")
AddHelpInfo("Spider Venom","Rumored that Man Eating Spider has a certain drop rate")
AddHelpInfo("Edgy Carapace","Rumored that Armored Crab has a certain drop rate")
AddHelpInfo("Frozen Conch Meat","Rumored that Northern Snail has a certain drop rate")
AddHelpInfo("Herbal Jelly","Rumored that War Tortoise has a certain drop rate")
AddHelpInfo("Well-Formed Tortoise Shell","Rumored that Mature Grass Tortoise has a certain drop rate")
AddHelpInfo("Heart of Purity","Rumored that Snow Spirit has a certain drop rate")
AddHelpInfo("Skeletal Bandana","Rumored that Sand Bandit Leader - Garet has a certain drop rate")
AddHelpInfo("Razor Sharp Tusk","Rumored that Mad Boar has a certain drop rate")
AddHelpInfo("Frosty Heart","Rumored that Fragile Snow Doll has a certain drop rate")
AddHelpInfo("Horse Whip","Rumored that Sand Raider has a certain drop rate")
AddHelpInfo("Chameleon Pig Trotter","Rumored that Combat Piglet has a certain drop rate")
AddHelpInfo("Blood Red Crab Carapace","Rumored that Armored King Crab has a certain drop rate")
AddHelpInfo("Vampiric Fangs","Rumored that Vampire Bat has a certain drop rate")
AddHelpInfo("Yeti Nail","Rumored that Yeti has a certain drop rate")
AddHelpInfo("Top Grade Deer Skin","Rumored that Grassland Elk has a certain drop rate")
AddHelpInfo("Lizard Crown","Rumored that Lizard King has a certain drop rate")
AddHelpInfo("Misshapen Demonic Blade","Rumored that Atrocious Yeti King has a certain drop rate")
AddHelpInfo("Swift Wolf Claw","Rumored that Grassland Wolf has a certain drop rate")
AddHelpInfo("Chilled Heart","Rumored that Playful Snow Doll has a certain drop rate")
AddHelpInfo("Miner Mole Safety Helmet","Rumored that Miner Mole has a certain drop rate")
AddHelpInfo("Green Boxing Gloves","Rumored that Berserk Boxeroo has a certain drop rate")
AddHelpInfo("Earthen Stone","Rumored that Battle Tortoise has a certain drop rate")
AddHelpInfo("Short Snail Feeler","Rumored that Slowpoke Snail has a certain drop rate")
AddHelpInfo("Pirate Hat","Rumored that Captain Fickle has a certain drop rate")
AddHelpInfo("Skeletal Ribs","Rumored that Skeletal Archer has a certain drop rate")
AddHelpInfo("Strange Candle","Rumored that Mud Monster has a certain drop rate")
AddHelpInfo("Sharp Beak","Rumored that White Owlie has a certain drop rate")
AddHelpInfo("Heated Tortoise Shell","Rumored that Snowy Tortoise has a certain drop rate")
AddHelpInfo("Dingle Bell","Rumored that Crazy Sheep has a certain drop rate")
AddHelpInfo("Glossy Feather","Rumored that Stinging Beak has a certain drop rate")
AddHelpInfo("Cracked Tortoise Egg","Rumored that Fearsome Tortoise has a certain drop rate")
AddHelpInfo("Great Bear Tooth","Rumored that Polar Bear has a certain drop rate")
AddHelpInfo("Ninja Sword","Rumored that Ninja Mole has a certain drop rate")
AddHelpInfo("Scorpion Blood","Rumored that Ferocious Scorpion has a certain drop rate")
AddHelpInfo("Rugged Pig Trotter","Rumored that Snowy Tusk Boar has a certain drop rate")
AddHelpInfo("Greasy Lizard Skin","Rumored that Thickskin Lizard has a certain drop rate")
AddHelpInfo("Slippery Rock","Rumored that Rock Golem has a certain drop rate")
AddHelpInfo("Warrior Certificate","Rumored that Skeletal Warrior has a certain drop rate")
AddHelpInfo("Thorny Water Shrub","Rumored that Seaweed has a certain drop rate")
AddHelpInfo("Long Tentacle","Rumored that Sea Jelly has a certain drop rate")
AddHelpInfo("Fresh Fish Meat","Rumored that Skeleton Fish has a certain drop rate")
AddHelpInfo("Tasty Squid Meat","Rumored that Baby Squid has a certain drop rate")
AddHelpInfo("Cracked Arabic Pearl","Rumored that Water Dancer has a certain drop rate")
AddHelpInfo("Shocking Tentacle","Rumored that Electric Sea Jelly has a certain drop rate")
AddHelpInfo("Polliwog Tail","Rumored that Blood Polliwog has a certain drop rate")
AddHelpInfo("Twinkling Merman Scale","Rumored that Mermaid has a certain drop rate")
AddHelpInfo("Large Tentacle","Rumored that Tempest Sea Jelly has a certain drop rate")
AddHelpInfo("Magical Stone Fragment","Rumored that Ruby Dolphin has a certain drop rate")
AddHelpInfo("Fish Spike","Rumored that Fish Bone has a certain drop rate")
AddHelpInfo("Gigantic Polliwog Tail","Rumored that Great Polliwog has a certain drop rate")
AddHelpInfo("Big Tail Scale","Rumored that Azure Siren has a certain drop rate")
AddHelpInfo("Shark Fin","Rumored that Sawtooth Shark has a certain drop rate")
AddHelpInfo("Mystic Crystal Fragment","Rumored that Crystalline Dolphin has a certain drop rate")
AddHelpInfo("Sparkling Fin","Rumored that Crimson Siren has a certain drop rate")
AddHelpInfo("Revival Flower","Rumored that Mermaid Queen has a certain drop rate")
AddHelpInfo("Panacea","Rumored that Siren Queen has a certain drop rate")
AddHelpInfo("","Rumored that there is a certain drop rate")
AddHelpInfo("Drop 2","Rumored that monsters has a certain drop rate")
AddHelpInfo("Thick Wolf Hide","Rumored that Wolf has a certain drop rate")
AddHelpInfo("Rusty Broadsword","Rumored that Cumbersome Snowman has a certain drop rate")
AddHelpInfo("Broken Hammer","Rumored that Werewolf Warrior has a certain drop rate")
AddHelpInfo("Long Stramonium Spike","Rumored that Spiky Stramonium has a certain drop rate")
AddHelpInfo("Broken Strange Bone","Rumored that Tribal Villager has a certain drop rate")
AddHelpInfo("Giant Broadsword","Rumored that Snowman has a certain drop rate")
AddHelpInfo("Steel Feeler","Rumored that Steel-shell Snail has a certain drop rate")
AddHelpInfo("Slipshod Wooden Stick","Rumored that Cumbersome Yeti has a certain drop rate")
AddHelpInfo("Death Arrow","Rumored that Undead Archer has a certain drop rate")
AddHelpInfo("Giant Wooden Stick","Rumored that Snow Yeti has a certain drop rate")
AddHelpInfo("Lantern","Rumored that Pumpkin Knight has a certain drop rate")
AddHelpInfo("Tribal Shield","Rumored that Tribal Warrior has a certain drop rate")
AddHelpInfo("Ruptured Rib","Rumored that Elite Skeletal Archer has a certain drop rate")
AddHelpInfo("Heart of Ice Crystal Fragment","Rumored that Infant Icy Dragon has a certain drop rate")
AddHelpInfo("Sandy Crab Meat","Rumored that Sand Crab has a certain drop rate")
AddHelpInfo("Withered Root","Rumored that Treant has a certain drop rate")
AddHelpInfo("Used Candle","Rumored that Dark Mud Monster has a certain drop rate")
AddHelpInfo("Razor Bear Tooth","Rumored that Great Polar Bear has a certain drop rate")
AddHelpInfo("Pure Crystal","Rumored that Water Fairy has a certain drop rate")
AddHelpInfo("Fearsome Sword of Giant","Rumored that Horrific Snowman has a certain drop rate")
AddHelpInfo("Broken Werewolf Bow","Rumored that Werewolf Archer has a certain drop rate")
AddHelpInfo("Shimmering Rock Fragment","Rumored that Sturdy Rock Golem has a certain drop rate")
AddHelpInfo("Wolf Hide Masterpiece","Rumored that Frenzied Wolf has a certain drop rate")
AddHelpInfo("Fearsome Staff of Giant","Rumored that Horrific Yeti has a certain drop rate")
AddHelpInfo("Sakura Bandana","Rumored that Sakura Pirate Sailor has a certain drop rate")
AddHelpInfo("Mark of Warrior Honor","Rumored that Elite Skeletal Warrior has a certain drop rate")
AddHelpInfo("Sakura Dirk","Rumored that Sakura Pirate Fighter has a certain drop rate")
AddHelpInfo("Sakura Sabre","Rumored that Sakura Pirate Militia has a certain drop rate")
AddHelpInfo("Unyielding Helmet","Rumored that Undead Warrior has a certain drop rate")
AddHelpInfo("Bloodied Hammer","Rumored that Elite Werewolf Warrior has a certain drop rate")
AddHelpInfo("Mummy Nail","Rumored that Iron Mummy has a certain drop rate")
AddHelpInfo("Huge Stramonium Thorn","Rumored that Huge Spiky Stramonium has a certain drop rate")
AddHelpInfo("Mummy Hair","Rumored that Steel Mummy has a certain drop rate")
AddHelpInfo("Tribal Mask","Rumored that Tribal Shaman has a certain drop rate")
AddHelpInfo("Lizard Man Axe","Rumored that Lizardman has a certain drop rate")
AddHelpInfo("Mysterious Bone","Rumored that Agile Tribal Villager has a certain drop rate")
AddHelpInfo("Broken Angel Wand","Rumored that Guardian Angel has a certain drop rate")
AddHelpInfo("Fallen Helmet","Rumored that Vicious Undead Warrior has a certain drop rate")
AddHelpInfo("Royal Saber","Rumored that Palace Guard has a certain drop rate")
AddHelpInfo("Northern Bandana","Rumored that Northern Pirate Sailor has a certain drop rate")
AddHelpInfo("Northern Dirk","Rumored that Northern Pirate Fighter has a certain drop rate")
AddHelpInfo("Complete Rib","Rumored that Deadly Skeletal Archer has a certain drop rate")
AddHelpInfo("Nothern Sabre","Rumored that Northern Pirate Militia has a certain drop rate")
AddHelpInfo("Dented Sacred Bow","Rumored that Forest Hunter has a certain drop rate")
AddHelpInfo("Warrior Leader Token","Rumored that Skeletal Warrior Leader has a certain drop rate")
AddHelpInfo("Skeleton Bone Fragment","Rumored that Cursed Corpse has a certain drop rate")
AddHelpInfo("Dark Bow","Rumored that Bloodthirsty Hunter has a certain drop rate")
AddHelpInfo("Terra Backpack","Rumored that Terra Soldier has a certain drop rate")
AddHelpInfo("Broken Navy Emblem","Rumored that Navy Rifleman has a certain drop rate")
AddHelpInfo("Thorny Wild Water Shrub","Rumored that Wild Seaweed has a certain drop rate")
AddHelpInfo("Thorny Floating Water Shrub","Rumored that Floating Seaweed has a certain drop rate")
AddHelpInfo("Thorny Rotten Water Shrub","Rumored that Icky Seaweed has a certain drop rate")
AddHelpInfo("Cursed Thorny Water Shrub","Rumored that Cursed Seaweed has a certain drop rate")
AddHelpInfo("White Sea Jelly Tentacle","Rumored that White Cap Sea Jelly has a certain drop rate")
AddHelpInfo("Bloody Sea Jelly Tentacle","Rumored that Man Eating Sea Jelly has a certain drop rate")
AddHelpInfo("Fishy Smelling Squid Meat","Rumored that Blackarrow Squid has a certain drop rate")
AddHelpInfo("Stretchy Fish Meat","Rumored that Swift Skeleton Fish has a certain drop rate")
AddHelpInfo("Black Fish Meat","Rumored that Tanned Skeleton Fish has a certain drop rate")
AddHelpInfo("Fatty Squid Meat","Rumored that Sluggish Squid has a certain drop rate")
AddHelpInfo("Arabic Pearl Fragment","Rumored that Ocean Water Dancer has a certain drop rate")
AddHelpInfo("Shadow Squid Meat","Rumored that Vicious Baby Squid has a certain drop rate")
AddHelpInfo("Devilish Arabic Pearl Fragment","Rumored that Evil Water Dancer has a certain drop rate")
AddHelpInfo("Virulent Sea Jelly Tentacle","Rumored that Poisonous Sea Jelly has a certain drop rate")
AddHelpInfo("Heavily Scarred Tentacle","Rumored that Raging Sea Jelly has a certain drop rate")
AddHelpInfo("Dark Black Squid Meat","Rumored that Blackout Squid has a certain drop rate")
AddHelpInfo("Salted Octopus Meat","Rumored that Octopus has a certain drop rate")
AddHelpInfo("Smelly Octopus Meat","Rumored that Chameleon Squid has a certain drop rate")
AddHelpInfo("Rotten Fish Meat","Rumored that Decaying Fish Bone has a certain drop rate")
AddHelpInfo("Evil Fish Meat","Rumored that Evil Skeleton Fish has a certain drop rate")
AddHelpInfo("Stretchy Squid Meat","Rumored that Swift Baby Squid has a certain drop rate")
AddHelpInfo("Flavoured Squid Meat","Rumored that Rapid Squid has a certain drop rate")
AddHelpInfo("Arabic Dark Pearl Fragment","Rumored that Midnight Water Dancer has a certain drop rate")
AddHelpInfo("Sparkling Arabic Pearl Fragment","Rumored that Swift Water Dancer has a certain drop rate")
AddHelpInfo("High Quality Tasty Fishmeat","Rumored that Feral Skeleton Fish has a certain drop rate")
AddHelpInfo("Electrifying Sea Jelly Tentacle","Rumored that Thunder Sea Jelly has a certain drop rate")
AddHelpInfo("High Voltage Tentacle","Rumored that Shocking Sea Jelly has a certain drop rate")
AddHelpInfo("Devilish Polliwog Tail","Rumored that Evil Blood Polliwog has a certain drop rate")
AddHelpInfo("Electric Tentacle","Rumored that Swift Electric Sea Jelly has a certain drop rate")
AddHelpInfo("Gigantic Polliwog Tail","Rumored that Feral Blood Polliwog has a certain drop rate")
AddHelpInfo("Transparent Polliwog Tail","Rumored that Stealth Blood Polliwog has a certain drop rate")
AddHelpInfo("Defiled Merman Scale","Rumored that Vicious Mermaid has a certain drop rate")
AddHelpInfo("Old Jack the Pirate Sail","Rumored that Jack the Pirate's Support Ship has a certain drop rate")
AddHelpInfo("Rusty Jack the Pirate Cannon","Rumored that Jack the Pirate's Warship has a certain drop rate")
AddHelpInfo("Intact Merman Scale","Rumored that Wandering Mermaid has a certain drop rate")
AddHelpInfo("Shadow Merman Scale","Rumored that Shadow Mermaid has a certain drop rate")
AddHelpInfo("Big Shark Dorsal Fin","Rumored that Old Sawtooth Shark has a certain drop rate")
AddHelpInfo("White Shark Dorsal Fin","Rumored that White Finned Shark has a certain drop rate")
AddHelpInfo("Jack the Pirate's Banner","Rumored that Jack the Pirate's Command Ship has a certain drop rate")
AddHelpInfo("Gigantic Shark Dorsal Fin","Rumored that Spearhead Shark has a certain drop rate")
AddHelpInfo("Black Shark Dorsal Fin","Rumored that Black Finned Shark has a certain drop rate")
AddHelpInfo("Old Sakura Pirate Sail","Rumored that Sakura 13 Support Ship has a certain drop rate")
AddHelpInfo("Sturdy Sea Jelly Tentacle","Rumored that Raging Electric Sea Jelly has a certain drop rate")
AddHelpInfo("Rusty Sakura Pirate Cannon","Rumored that Sakura 13 Warship has a certain drop rate")
AddHelpInfo("Bloody Polliwog Tail","Rumored that Vampiric Polliwog has a certain drop rate")
AddHelpInfo("Tempest Sea Jelly Tentacle","Rumored that Tempest Sea Jelly has a certain drop rate")
AddHelpInfo("Razor Sharp Dorsal Fin","Rumored that Silk Shark has a certain drop rate")
AddHelpInfo("Mysterious Topaz Fragment","Rumored that Topaz Dolphin has a certain drop rate")
AddHelpInfo("Hurricane Tentacle","Rumored that Hurricane Sea Jelly has a certain drop rate")
AddHelpInfo("Large Ruby Fragment","Rumored that Mature Ruby Dolphin has a certain drop rate")
AddHelpInfo("Sakura Pirate Banner","Rumored that Sakura 13 Pirate Command Ship has a certain drop rate")
AddHelpInfo("Long Fish Bone","Rumored that Spiny Fish Bone has a certain drop rate")
AddHelpInfo("Old Northern Pirate Sail","Rumored that Northern Pirate Support Ship has a certain drop rate")
AddHelpInfo("Thick Fish Bone","Rumored that Hungry Fish Bone has a certain drop rate")
AddHelpInfo("Rusty Northern Pirate Cannon","Rumored that Northern Pirate Warship has a certain drop rate")
AddHelpInfo("Heart of Giant","Rumored that Stone Golem has a certain drop rate")
AddHelpInfo("Small Magnet","Rumored that Iron Golem has a certain drop rate")
AddHelpInfo("Damaged Lizardman Blade","Rumored that Lizard Warrior has a certain drop rate")
AddHelpInfo("Strange Leaves","Rumored that Small Treant has a certain drop rate")
AddHelpInfo("Giant Skin","Rumored that Giant Lizard has a certain drop rate")
AddHelpInfo("Long Crab Shell","Rumored that Long Hair Crab has a certain drop rate")
AddHelpInfo("Cursed Carcass","Rumored that Horrific Cursed Corpse has a certain drop rate")
AddHelpInfo("Rusty Lantern","Rumored that Vicious Pumpkin Knight has a certain drop rate")
AddHelpInfo("Scorpion Claw","Rumored that Chimera has a certain drop rate")
AddHelpInfo("Solid Tribal Shield","Rumored that Elite Tribal Warrior has a certain drop rate")
AddHelpInfo("Treant Root","Rumored that Treant Terror has a certain drop rate")
AddHelpInfo("Rusty Terra Battle Armor","Rumored that Terra Warrior has a certain drop rate")
AddHelpInfo("Piece of Crystalline Heart","Rumored that Baby Icy Dragon has a certain drop rate")
AddHelpInfo("Broken Werewolf Long Bow","Rumored that Elite Werewolf Archer has a certain drop rate")
AddHelpInfo("Mysterious Bone","Rumored that Mad Tribal Villager has a certain drop rate")
AddHelpInfo("Evil Helmet","Rumored that Evil Undead Warrior has a certain drop rate")
AddHelpInfo("Extinguished Lantern","Rumored that Evil Pumpkin Knight has a certain drop rate")
AddHelpInfo("Blood Drenched Hammer","Rumored that Werewolf Warrior Leader has a certain drop rate")
AddHelpInfo("Tattered Shadow Shell","Rumored that Shadow Hunter has a certain drop rate")
AddHelpInfo("Royal Sword","Rumored that Palace Guard has a certain drop rate")
AddHelpInfo("Mysterious Leaf","Rumored that Lumbering Treant has a certain drop rate")
AddHelpInfo("Black Crystal","Rumored that Cursed Water Fairy has a certain drop rate")
AddHelpInfo("Cracked Angel Wand","Rumored that Corrupted Guardian Angel has a certain drop rate")
AddHelpInfo("Large Tribal Mask","Rumored that Mad Tribal Witchdoctor has a certain drop rate")
AddHelpInfo("Heavy Lizardman Battleaxe","Rumored that Frenzied Lizardman has a certain drop rate")
AddHelpInfo("Broken Bow of the Forest","Rumored that Nimble Forest Hunter has a certain drop rate")
AddHelpInfo("Broken Golden Kitty Bell","Rumored that White Bobcat has a certain drop rate")
AddHelpInfo("Broken terra smoking pipe","Rumored that Terra Elder has a certain drop rate")
AddHelpInfo("Terra Glasses","Rumored that Terra Artificer has a certain drop rate")
AddHelpInfo("Damaged Terra Battle Armor","Rumored that Terra Captain has a certain drop rate")
AddHelpInfo("Dark Bow of Blood","Rumored that Nimble Shadow Hunter has a certain drop rate")
AddHelpInfo("Refined Terra Backpack","Rumored that Terra Soldier Leader has a certain drop rate")
AddHelpInfo("Heavy Lizardman Broadsword","Rumored that Elite Lizardman Warrior has a certain drop rate")
AddHelpInfo("Lizardman Leader Battleaxe","Rumored that Lizard Warrior Leader has a certain drop rate")
AddHelpInfo("Refined Terra Battle Armor","Rumored that Elite Terra Warrior has a certain drop rate")
AddHelpInfo("Terra Captain Battle Armor","Rumored that Terra Warrior Leader has a certain drop rate")
AddHelpInfo("Broken Black Bobcat Bell","Rumored that Black Bobcat has a certain drop rate")
AddHelpInfo("Old Tobacco Pipe","Rumored that Vicious Grassland Elder has a certain drop rate")
AddHelpInfo("High Grade Terra Glasses","Rumored that Terra Artificer Leader has a certain drop rate")
AddHelpInfo("Shadowy Coat","Rumored that Elite Shadow Hunter has a certain drop rate")
AddHelpInfo("Golden Cat Bell","Rumored that Feral White Bobcat has a certain drop rate")
AddHelpInfo("Excellent Werewolf Long Bow","Rumored that Deadly Werewolf Archer has a certain drop rate")
AddHelpInfo("Black Cat Bell","Rumored that Feral Black Bobcat has a certain drop rate")
AddHelpInfo("Chimera Claw","Rumored that Frost Chimera has a certain drop rate")
AddHelpInfo("Corrupted Angel Wand","Rumored that Evil Guardian Angel has a certain drop rate")
AddHelpInfo("Cursed Golden Bell","Rumored that Cursed White Bobcat has a certain drop rate")
AddHelpInfo("Evil Tribal Mask","Rumored that Evil Tribal Shaman has a certain drop rate")
AddHelpInfo("Large Lizardman Battleaxe","Rumored that Frantic Lizardman has a certain drop rate")
AddHelpInfo("Bloodied Bow of Nature","Rumored that Ruthless Forest Hunter has a certain drop rate")
AddHelpInfo("Cursed Black Bell","Rumored that Cursed Black Bobcat has a certain drop rate")
AddHelpInfo("Piece of Armor Plate","Rumored that Relic Guard has a certain drop rate")
AddHelpInfo("Bloodied Bow","Rumored that Ruthless Shadow Hunter has a certain drop rate")
AddHelpInfo("Anubis Teeth","Rumored that Anubis has a certain drop rate")
AddHelpInfo("Metal Funnel","Rumored that Relic Protector has a certain drop rate")
AddHelpInfo("Staff of Kings","Rumored that Dharma Pharaoh has a certain drop rate")
AddHelpInfo("Red Beardy Bandana","Rumored that Beardy Pirate Sailor has a certain drop rate")
AddHelpInfo("Red Beardy Dirk","Rumored that Beardy Pirate Fighter has a certain drop rate")
AddHelpInfo("Red Beardy Sabre","Rumored that Beardy Pirate Militia has a certain drop rate")
AddHelpInfo("Rotten Small Fish Bone","Rumored that Decaying Fish Bone has a certain drop rate")
AddHelpInfo("Rigid Polliwog Tail","Rumored that Big Eyed Polliwog has a certain drop rate")
AddHelpInfo(" Evilish Polliwog Tail","Rumored that Evil Great Polliwog has a certain drop rate")
AddHelpInfo("Sturdy Polliwog Tail","Rumored that Great Feral Polliwog has a certain drop rate")
AddHelpInfo("Northern Pirate Banner","Rumored that Northern Pirate Command Ship has a certain drop rate")
AddHelpInfo("Strong Sea Jelly Tentacle","Rumored that Swift Cyclonic Sea Jelly has a certain drop rate")
AddHelpInfo("Cursed Merman Tail","Rumored that Cursed Mermaid has a certain drop rate")
AddHelpInfo("Powerful Sea Jelly Tentacle","Rumored that Raging Cyclonic Sea Jelly has a certain drop rate")
AddHelpInfo("Flawed Mysterious Ruby","Rumored that Old Ruby Dolphin has a certain drop rate")
AddHelpInfo("Razor Sharp Fish Bone","Rumored that Feral Fish Bone has a certain drop rate")
AddHelpInfo("Thick Transparent Polliwog Tail","Rumored that Great Prowling Polliwog has a certain drop rate")
AddHelpInfo("Small Mysterious Ruby","Rumored that Feral Ruby Dolphin has a certain drop rate")
AddHelpInfo("Glimmering Scale","Rumored that Bewitching Siren has a certain drop rate")
AddHelpInfo("Mysterious Amethyst Fragment","Rumored that Amethyst Dolphin has a certain drop rate")
AddHelpInfo("Flawed Mysterious Crystal","Rumored that Old Diamond Dolphin has a certain drop rate")
AddHelpInfo("Blue Ray Scale","Rumored that Dark Blue Siren has a certain drop rate")
AddHelpInfo("Siren Arrow Pouch","Rumored that Siren Archer has a certain drop rate")
AddHelpInfo("Old Beardy Pirate Sail","Rumored that Beardy Pirate Support Ship has a certain drop rate")
AddHelpInfo("Rusty Beardy Pirate Cannon","Rumored that Beardy Pirate Warship has a certain drop rate")
AddHelpInfo("Small Mysterious Crystal","Rumored that Feral Diamond Dolphin has a certain drop rate")
AddHelpInfo("Strong Ray Scale","Rumored that Frenzied Siren has a certain drop rate")
AddHelpInfo("Cracked Merman Card","Rumored that Berserk Mermaid Protector has a certain drop rate")
AddHelpInfo("Cracked Siren Card","Rumored that Berserk Siren Guard has a certain drop rate")
AddHelpInfo("Ancient Scale","Rumored that Ancient Siren has a certain drop rate")
AddHelpInfo("Beardy Pirate Banner","Rumored that Beardy Pirate Command Ship has a certain drop rate")
AddHelpInfo("Ancient Arrow Quiver","Rumored that Ancient Siren Archer has a certain drop rate")
AddHelpInfo("Corrupted Merman Card","Rumored that Tanned Mermaid Protector has a certain drop rate")
AddHelpInfo("Corrupted Siren Card","Rumored that Tanned Siren Guard has a certain drop rate")
AddHelpInfo("Chipped Merman Card","Rumored that Horrific Mermaid Protector has a certain drop rate")
AddHelpInfo("Chipped Siren Card","Rumored that Horrific Siren Guard has a certain drop rate")
AddHelpInfo("Wicked Scale","Rumored that Feral Siren has a certain drop rate")
AddHelpInfo("Shadowy Scale","Rumored that Shadow Siren has a certain drop rate")
AddHelpInfo("Ancient Glimmering Scale","Rumored that Ancient Bewitching Siren has a certain drop rate")
AddHelpInfo("Ancient Blue Scale","Rumored that Ancient Dark Blue Siren has a certain drop rate")
AddHelpInfo("Ancient Merman Card","Rumored that Ancient Mermaid Protector has a certain drop rate")
AddHelpInfo("Ancient Siren Card","Rumored that Ancient Siren Guard has a certain drop rate")
AddHelpInfo("Jack's Sailor Bandana","Rumored that Jack the Pirate's Sailor has a certain drop rate")
AddHelpInfo("Jack's Fighter Dagger","Rumored that Jack the Pirate's Fighter has a certain drop rate")
AddHelpInfo("Jack's Militia Sword","Rumored that Jack the Pirate's Militia has a certain drop rate")
AddHelpInfo("Master Key","Rumored that Cavalier has a certain drop rate")
AddHelpInfo("Dazzling Sword","Rumored that Jack - Black Sail has a certain drop rate")



