print("‡ £àã§ª  ItemAttrType.lua")

ITEMATTR_COUNT_BASE0    = 0;
ITEMATTR_COE_STR        = ITEMATTR_COUNT_BASE0 + 1; 
ITEMATTR_COE_AGI        = ITEMATTR_COUNT_BASE0 + 2; 
ITEMATTR_COE_DEX        = ITEMATTR_COUNT_BASE0 + 3; 
ITEMATTR_COE_CON        = ITEMATTR_COUNT_BASE0 + 4; 
ITEMATTR_COE_STA        = ITEMATTR_COUNT_BASE0 + 5; 
ITEMATTR_COE_LUK        = ITEMATTR_COUNT_BASE0 + 6; 
ITEMATTR_COE_ASPD       = ITEMATTR_COUNT_BASE0 + 7; 
ITEMATTR_COE_ADIS       = ITEMATTR_COUNT_BASE0 + 8; 
ITEMATTR_COE_MNATK      = ITEMATTR_COUNT_BASE0 + 9; 
ITEMATTR_COE_MXATK      = ITEMATTR_COUNT_BASE0 + 10; 
ITEMATTR_COE_DEF        = ITEMATTR_COUNT_BASE0 + 11; 
ITEMATTR_COE_MXHP       = ITEMATTR_COUNT_BASE0 + 12; 
ITEMATTR_COE_MXSP       = ITEMATTR_COUNT_BASE0 + 13; 
ITEMATTR_COE_FLEE       = ITEMATTR_COUNT_BASE0 + 14; 
ITEMATTR_COE_HIT        = ITEMATTR_COUNT_BASE0 + 15; 
ITEMATTR_COE_CRT        = ITEMATTR_COUNT_BASE0 + 16; 
ITEMATTR_COE_MF         = ITEMATTR_COUNT_BASE0 + 17; 
ITEMATTR_COE_HREC       = ITEMATTR_COUNT_BASE0 + 18; 
ITEMATTR_COE_SREC       = ITEMATTR_COUNT_BASE0 + 19; 
ITEMATTR_COE_MSPD       = ITEMATTR_COUNT_BASE0 + 20; 
ITEMATTR_COE_COL        = ITEMATTR_COUNT_BASE0 + 21; 
ITEMATTR_COE_PDEF       = ITEMATTR_COUNT_BASE0 + 22; 

ITEMATTR_COUNT_BASE1    = 25;
ITEMATTR_VAL_STR        = ITEMATTR_COUNT_BASE1 + 1; 
ITEMATTR_VAL_AGI        = ITEMATTR_COUNT_BASE1 + 2; 
ITEMATTR_VAL_DEX        = ITEMATTR_COUNT_BASE1 + 3; 
ITEMATTR_VAL_CON        = ITEMATTR_COUNT_BASE1 + 4; 
ITEMATTR_VAL_STA        = ITEMATTR_COUNT_BASE1 + 5; 
ITEMATTR_VAL_LUK        = ITEMATTR_COUNT_BASE1 + 6; 
ITEMATTR_VAL_ASPD       = ITEMATTR_COUNT_BASE1 + 7; 
ITEMATTR_VAL_ADIS       = ITEMATTR_COUNT_BASE1 + 8; 
ITEMATTR_VAL_MNATK      = ITEMATTR_COUNT_BASE1 + 9; 
ITEMATTR_VAL_MXATK      = ITEMATTR_COUNT_BASE1 + 10; 
ITEMATTR_VAL_DEF        = ITEMATTR_COUNT_BASE1 + 11; 
ITEMATTR_VAL_MXHP       = ITEMATTR_COUNT_BASE1 + 12; 
ITEMATTR_VAL_MXSP       = ITEMATTR_COUNT_BASE1 + 13; 
ITEMATTR_VAL_FLEE       = ITEMATTR_COUNT_BASE1 + 14; 
ITEMATTR_VAL_HIT        = ITEMATTR_COUNT_BASE1 + 15; 
ITEMATTR_VAL_CRT        = ITEMATTR_COUNT_BASE1 + 16; 
ITEMATTR_VAL_MF         = ITEMATTR_COUNT_BASE1 + 17; 
ITEMATTR_VAL_HREC       = ITEMATTR_COUNT_BASE1 + 18; 
ITEMATTR_VAL_SREC       = ITEMATTR_COUNT_BASE1 + 19; 
ITEMATTR_VAL_MSPD       = ITEMATTR_COUNT_BASE1 + 20; 
ITEMATTR_VAL_COL        = ITEMATTR_COUNT_BASE1 + 21; 
ITEMATTR_VAL_PDEF       = ITEMATTR_COUNT_BASE1 + 22; 

ITEMATTR_COUNT_BASE2    = 49;
ITEMATTR_LHAND_VAL      = ITEMATTR_COUNT_BASE2 + 1; 
ITEMATTR_MAXURE	        = ITEMATTR_COUNT_BASE2 + 2; 
ITEMATTR_MAXFORGE       = ITEMATTR_COUNT_BASE2 + 3; 
ITEMATTR_MAXENERGY      = ITEMATTR_COUNT_BASE2 + 4; 
ITEMATTR_URE            = ITEMATTR_COUNT_BASE2 + 5; 
ITEMATTR_FORGE          = ITEMATTR_COUNT_BASE2 + 6;
ITEMATTR_ENERGY         = ITEMATTR_COUNT_BASE2 + 7;


ITEMATTR_MAX_NUM        = 58;
ITEMATTR_CLIENT_MAX     = ITEMATTR_VAL_PDEF + 1;    

ITEMATTR_COUNT_BASE3    = 180;
ITEMATTR_VAL_PARAM1		= ITEMATTR_COUNT_BASE3 + 1;	
ITEMATTR_VAL_PARAM2		= ITEMATTR_COUNT_BASE3 + 2;	
ITEMATTR_VAL_LEVEL		= ITEMATTR_COUNT_BASE3 + 3; 
ITEMATTR_VAL_FUSIONID   = ITEMATTR_COUNT_BASE3 + 4; 

ITEMATTR_VAL_BaoshiLV = ITEMATTR_MAXENERGY --±¦Ê¯µÈ¼¶