print("Загрузка SkillStateType.lua")

SSTATE_CUT		= 1;	
SSTATE_FERVOR_ARROR	= 2;	
SSTATE_FROST_ARROR	= 3;	
SSTATE_SKYROCKET	= 4;	
SSTATE_MURRAIN		= 5;	
SSTATE_GIDDY		= 6;	
SSTATE_FREEZE		= 7;	
SSTATE_SLEEP		= 8;	
SSTATE_BIND		= 9;	
SSTATE_FROST		= 10;	
SSTATE_BEAT_BACK	= 11;	
SSTATE_UNBEATABLE	= 12;	
SSTATE_TOXIN		= 13;	
SSTATE_REBOUND		= 14;	
SSTATE_AVATAR		= 15;	
SSTATE_TITAN		= 16;	
SSTATE_BLINDNESS	= 17;	
SSTATE_CHANGE		= 18;	
SSTATE_FLOAT		= 19;	
SSTATE_CALL		= 20;	
SSTATE_SHIELD		= 21;	